import React, { useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { blockChatUser, fetchMessengerContacts, MessengerContact } from '../api/marketplace';
import { useAuth } from '../auth/AuthContext';
import RemoteImage from '../components/RemoteImage';
import { EmptyState, ErrorState, LoadingState } from '../components/StateViews';

export default function BlockedContactsScreen() {
  const navigation=useNavigation<any>(); const qc=useQueryClient(); const {activeRole}=useAuth(); const [search,setSearch]=useState('');
  const query=useQuery({queryKey:['messenger-contacts',activeRole],queryFn:()=>fetchMessengerContacts(activeRole)});
  const contacts=useMemo(()=>(query.data?.blockedUsers??[]).filter(item=>`${item.name} ${item.email??''}`.toLowerCase().includes(search.toLowerCase())),[query.data?.blockedUsers,search]);
  const unblock=useMutation({mutationFn:(item:MessengerContact)=>blockChatUser(item.chatId,false),onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:['messenger-contacts']}),qc.invalidateQueries({queryKey:['chats']}),qc.invalidateQueries({queryKey:['chat-details']})]);},onError:e=>Alert.alert('Unable to unblock',e instanceof Error?e.message:'Please try again.')});
  return <View style={s.screen}><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.icon}><Icon name="arrow-left" size={23} color="#111827"/></Pressable><View style={s.headerBody}><Text style={s.title}>Blocked contacts</Text><Text style={s.subtitle}>Manage people who cannot message you</Text></View></View><View style={s.search}><Icon name="magnify" size={20} color="#94A3B8"/><TextInput value={search} onChangeText={setSearch} placeholder="Search blocked contacts" placeholderTextColor="#94A3B8" style={s.input}/></View>{query.isLoading?<LoadingState label="Loading blocked contacts"/>:query.isError?<ErrorState message={(query.error as Error).message} onRetry={()=>query.refetch()}/>:<FlatList data={contacts} keyExtractor={item=>item.chatId} contentContainerStyle={s.list} ListEmptyComponent={<EmptyState title="No blocked contacts" detail="Contacts you block will remain manageable here."/>} renderItem={({item})=><View style={s.card}><RemoteImage uri={item.avatarUrl} width={96} height={96} style={s.avatar} fallback={<View style={s.fallback}><Text style={s.initial}>{item.name?.[0]?.toUpperCase()??'?'}</Text></View>}/><View style={s.body}><Text style={s.name}>{item.name}</Text><Text style={s.meta}>{item.email||`${item.type??'contact'} · blocked`}</Text><View style={s.actions}><Pressable onPress={()=>navigation.navigate('ChatDetails',{chatId:item.chatId,title:item.name})}><Text style={s.profile}>View conversation</Text></Pressable><Pressable disabled={unblock.isPending} onPress={()=>unblock.mutate(item)} style={s.unblock}><Text style={s.unblockText}>UNBLOCK</Text></Pressable></View></View></View>}/>}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8FAFC'},header:{paddingTop:52,paddingHorizontal:16,paddingBottom:14,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#FFF'},icon:{width:42,height:42,borderRadius:13,backgroundColor:'#F8FAFC',alignItems:'center',justifyContent:'center'},headerBody:{flex:1},title:{fontSize:19,fontWeight:'900',color:'#111827'},subtitle:{fontSize:11,color:'#64748B',marginTop:2},search:{margin:16,height:48,borderRadius:14,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:14,borderWidth:1,borderColor:'#E2E8F0'},input:{flex:1,color:'#111827'},list:{paddingHorizontal:16,paddingBottom:50},card:{backgroundColor:'#FFF',borderRadius:17,padding:14,marginBottom:10,flexDirection:'row',gap:12},avatar:{width:52,height:52,borderRadius:16},fallback:{width:52,height:52,borderRadius:16,backgroundColor:'#FFF3E8',alignItems:'center',justifyContent:'center'},initial:{fontSize:19,fontWeight:'900',color:'#F26A21'},body:{flex:1},name:{fontSize:15,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#64748B',marginTop:3},actions:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:11},profile:{fontSize:11,fontWeight:'800',color:'#475569'},unblock:{backgroundColor:'#F26A21',borderRadius:9,paddingHorizontal:12,paddingVertical:7},unblockText:{color:'#FFF',fontSize:10,fontWeight:'900'}});
