import React, { useState } from 'react';
import { Alert, LayoutAnimation, Linking, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, UIManager, View } from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import { useMutation } from '@tanstack/react-query';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { createSupportTicket } from '../api/support';
import { useAuth } from '../auth/AuthContext';
import { LEGAL_LINKS, SUPPORT_CONTACTS } from '../config/support';

if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) UIManager.setLayoutAnimationEnabledExperimental(true);
const FAQS = [
  ['How do I place an enquiry?', 'Open a product, choose Send Enquiry, enter your quantity and requirements, then submit it to the supplier.'],
  ['How do I contact suppliers?', 'Use Chat Now on a product or supplier page. Your conversations remain available under Messages.'],
  ['How do I verify manufacturers?', 'Look for verified badges and review the supplier profile, certificates, factory details, ratings, and transaction history.'],
  ['How do I edit my profile or address?', 'Open Account, then Profile Settings or Manage Addresses.'],
  ['How are payments protected?', 'Eligible orders support platform payment and escrow flows. Confirm the order summary before payment.'],
  ['How does shipping work?', 'Shipping methods, estimated delivery, charges, and trade terms appear during checkout or quotation review.'],
];

export default function HelpSupportScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const [expanded, setExpanded] = useState<number | null>(() => route.params?.focus === 'faq' ? 0 : null);
  const { activeRole } = useAuth();
  const [form, setForm] = useState({ name: '', email: '', subject: '', message: '' });
  const contact = useMutation({ mutationFn: (input: typeof form) => createSupportTicket({ subject: input.subject, description: input.message, roleContext: activeRole === 'seller' ? 'seller' : 'buyer', issueType: 'other', priority: 'medium', metadata: { contactName: input.name, contactEmail: input.email } }), onSuccess: () => { setForm({ name: '', email: '', subject: '', message: '' }); Alert.alert('Ticket raised', 'Your ticket is open and synchronized with EsyGlob support.'); }, onError: error => Alert.alert('Unable to submit', error instanceof Error ? error.message : 'Please try again.') });
  const open = (url: string) => Linking.openURL(url).catch(() => Alert.alert('Unable to open', 'No compatible app is available.'));
  const submit = () => { if (!form.name.trim() || !/^\S+@\S+\.\S+$/.test(form.email) || form.subject.trim().length < 2 || form.message.trim().length < 10) { Alert.alert('Complete the form', 'Enter your name, valid email, subject, and a message of at least 10 characters.'); return; } contact.mutate(form); };
  return <SafeAreaView style={s.screen}><View style={s.header}><Pressable onPress={() => navigation.goBack()} style={s.iconButton}><Icon name="arrow-left" size={22} color="#111827" /></Pressable><Text style={s.headerTitle}>Help & Support</Text><View style={s.iconButton} /></View><ScrollView contentContainerStyle={s.content}>
    <View style={s.hero}><View style={s.heroIcon}><Icon name="headset" size={30} color="#FFF" /></View><View style={s.flex}><Text style={s.heroTitle}>How can we help?</Text><Text style={s.heroText}>Talk to our team or get instant guidance from EsyGlob AI.</Text></View></View>
    <Title text="Contact support" />
    <View style={s.card}><Contact icon="phone-outline" label="Customer support" value={SUPPORT_CONTACTS.customerSupport} onPress={() => open(`tel:${SUPPORT_CONTACTS.customerSupport.replace(/\s/g, '')}`)} /><Contact icon="whatsapp" label="WhatsApp" value={SUPPORT_CONTACTS.whatsapp} onPress={() => open(`https://wa.me/${SUPPORT_CONTACTS.whatsapp.replace(/\D/g, '')}`)} /><Contact icon="briefcase-outline" label="Sales" value={SUPPORT_CONTACTS.sales} onPress={() => open(`tel:${SUPPORT_CONTACTS.sales.replace(/\s/g, '')}`)} /><Contact icon="email-outline" label="Support email" value={SUPPORT_CONTACTS.supportEmail} onPress={() => open(`mailto:${SUPPORT_CONTACTS.supportEmail}`)} /><Contact icon="domain" label="Business email" value={SUPPORT_CONTACTS.businessEmail} onPress={() => open(`mailto:${SUPPORT_CONTACTS.businessEmail}`)} last /></View>
    <Pressable onPress={() => navigation.navigate('AIChat')} style={s.aiCard}><View style={s.aiIcon}><Icon name="robot-excited-outline" size={27} color="#FFF" /></View><View style={s.flex}><Text style={s.aiTitle}>Need instant help?</Text><Text style={s.aiText}>Ask the existing EsyGlob AI assistant.</Text></View><View style={s.aiButton}><Text style={s.aiButtonText}>Chat with AI</Text></View></Pressable>
    <Title text="Frequently asked questions" />
    <View style={s.card}>{FAQS.map(([question, answer], index) => <Pressable key={question} onPress={() => { LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut); setExpanded(expanded === index ? null : index); }} style={s.faq}><View style={s.faqTop}><Text style={s.faqQuestion}>{question}</Text><Icon name={expanded === index ? 'chevron-up' : 'chevron-down'} size={20} color="#6B7280" /></View>{expanded === index ? <Text style={s.faqAnswer}>{answer}</Text> : null}</Pressable>)}</View>
    <Title text="Send us a message" /><View style={s.cardPad}><Input label="Name" value={form.name} onChangeText={name => setForm({ ...form, name })} /><Input label="Email" value={form.email} onChangeText={email => setForm({ ...form, email })} keyboardType="email-address" /><Input label="Subject" value={form.subject} onChangeText={subject => setForm({ ...form, subject })} /><Input label="Message" value={form.message} onChangeText={message => setForm({ ...form, message })} multiline /><Pressable disabled={contact.isPending} onPress={submit} style={s.submit}><Text style={s.submitText}>{contact.isPending ? 'Sending…' : 'Submit request'}</Text></Pressable></View>
    <Title text="App information" /><View style={s.card}><Contact icon="information-outline" label="EsyGlob" value="Version 1.0.0 · Build 1" onPress={() => undefined} /><Contact icon="shield-lock-outline" label="Privacy Policy" value="Read policy" onPress={() => open(LEGAL_LINKS.privacy)} /><Contact icon="file-document-outline" label="Terms & Conditions" value="Read terms" onPress={() => open(LEGAL_LINKS.terms)} /><Contact icon="domain" label="About EsyGlob" value="Company information" onPress={() => open(LEGAL_LINKS.about)} last /></View>
  </ScrollView></SafeAreaView>;
}
function Title({ text }: { text: string }) { return <Text style={s.title}>{text}</Text>; }
function Contact({ icon, label, value, onPress, last }: { icon: string; label: string; value: string; onPress: () => void; last?: boolean }) { return <Pressable accessibilityRole="button" onPress={onPress} style={[s.contact, last && s.last]}><View style={s.contactIcon}><Icon name={icon} size={20} color="#2563EB" /></View><View style={s.flex}><Text style={s.contactLabel}>{label}</Text><Text style={s.contactValue}>{value}</Text></View><Icon name="chevron-right" size={20} color="#9CA3AF" /></Pressable>; }
function Input({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#9CA3AF" style={[s.input, props.multiline && s.multiline]} {...props} /></View>; }
const s = StyleSheet.create({ screen:{flex:1,backgroundColor:'#F5F7FA'},header:{height:56,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#E5E7EB',paddingHorizontal:12},iconButton:{width:40,height:40,alignItems:'center',justifyContent:'center'},headerTitle:{flex:1,textAlign:'center',fontSize:17,fontWeight:'800',color:'#111827'},content:{padding:14,paddingBottom:40},hero:{backgroundColor:'#111827',borderRadius:18,padding:18,flexDirection:'row',gap:14,alignItems:'center'},heroIcon:{width:54,height:54,borderRadius:16,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center'},flex:{flex:1},heroTitle:{fontSize:20,fontWeight:'800',color:'#FFF'},heroText:{fontSize:12,lineHeight:18,color:'#CBD5E1',marginTop:3},title:{fontSize:15,fontWeight:'800',color:'#111827',marginTop:22,marginBottom:9},card:{backgroundColor:'#FFF',borderRadius:16,borderWidth:1,borderColor:'#E5E7EB',overflow:'hidden'},cardPad:{backgroundColor:'#FFF',borderRadius:16,borderWidth:1,borderColor:'#E5E7EB',padding:14},contact:{minHeight:68,padding:12,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:'#EEF0F3'},last:{borderBottomWidth:0},contactIcon:{width:40,height:40,borderRadius:12,backgroundColor:'#EFF6FF',alignItems:'center',justifyContent:'center'},contactLabel:{fontSize:13,fontWeight:'700',color:'#111827'},contactValue:{fontSize:11,color:'#6B7280',marginTop:3},aiCard:{marginTop:14,padding:15,borderRadius:17,backgroundColor:'#EEF2FF',borderWidth:1,borderColor:'#C7D2FE',flexDirection:'row',gap:11,alignItems:'center'},aiIcon:{width:48,height:48,borderRadius:14,backgroundColor:'#6366F1',alignItems:'center',justifyContent:'center'},aiTitle:{fontSize:15,fontWeight:'800',color:'#312E81'},aiText:{fontSize:11,color:'#6366F1',marginTop:3},aiButton:{backgroundColor:'#4F46E5',paddingHorizontal:10,paddingVertical:8,borderRadius:9},aiButtonText:{color:'#FFF',fontSize:10,fontWeight:'800'},faq:{padding:14,borderBottomWidth:1,borderBottomColor:'#EEF0F3'},faqTop:{flexDirection:'row',alignItems:'center',gap:8},faqQuestion:{flex:1,fontSize:13,fontWeight:'700',color:'#111827'},faqAnswer:{fontSize:12,lineHeight:19,color:'#6B7280',marginTop:9},field:{marginBottom:12},label:{fontSize:11,fontWeight:'700',color:'#374151',marginBottom:6},input:{minHeight:45,borderWidth:1,borderColor:'#D1D5DB',borderRadius:10,paddingHorizontal:12,color:'#111827',backgroundColor:'#FAFAFA'},multiline:{height:110,textAlignVertical:'top',paddingTop:12},submit:{height:48,borderRadius:11,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center'},submitText:{color:'#FFF',fontWeight:'800',fontSize:13} });
