import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

type HSRecord={code:string;name:string;category:string;subcategory:string;description:string;keywords:string[];related:string[]};
const STARTER:HSRecord[]=[
  {code:'0901.21',name:'Roasted coffee',category:'Food & Agriculture',subcategory:'Coffee and spices',description:'Roasted coffee, whether or not decaffeinated.',keywords:['coffee','beans','roasted'],related:['0901.11','0901.12']},
  {code:'1006.30',name:'Semi-milled or wholly milled rice',category:'Food & Agriculture',subcategory:'Cereals',description:'Rice that has been semi-milled or wholly milled, whether or not polished or glazed.',keywords:['rice','basmati','grain'],related:['1006.10','1006.20']},
  {code:'6109.10',name:'Cotton T-shirts',category:'Textiles & Apparel',subcategory:'Knitted garments',description:'T-shirts, singlets and other vests, knitted or crocheted, of cotton.',keywords:['tshirt','t-shirt','cotton','apparel'],related:['6109.90','6110.20']},
  {code:'6403.99',name:'Footwear with leather uppers',category:'Footwear',subcategory:'Leather footwear',description:'Other footwear with outer soles of rubber, plastics or leather and uppers of leather.',keywords:['shoe','shoes','leather','footwear'],related:['6403.19','6403.59']},
  {code:'8504.40',name:'Static converters',category:'Electrical & Electronics',subcategory:'Power equipment',description:'Electrical static converters including power adapters, inverters and rectifiers.',keywords:['adapter','charger','inverter','converter'],related:['8504.31','8504.50']},
  {code:'8517.13',name:'Smartphones',category:'Electrical & Electronics',subcategory:'Telecommunications',description:'Smartphones for cellular or other wireless networks.',keywords:['phone','mobile','smartphone'],related:['8517.14','8517.62']},
  {code:'9403.60',name:'Other wooden furniture',category:'Furniture',subcategory:'Wood furniture',description:'Wooden furniture other than office, kitchen or bedroom furniture.',keywords:['furniture','wood','table','cabinet'],related:['9403.30','9403.40']},
  {code:'9503.00',name:'Toys and models',category:'Toys & Games',subcategory:'General toys',description:'Tricycles, scooters, dolls, construction sets, puzzles and other toys.',keywords:['toy','toys','puzzle','doll'],related:['9504.40','9504.90']},
];
export default function HSCodeFinderScreen(){const nav=useNavigation<any>();const [q,setQ]=useState('');const results=useMemo(()=>{const term=q.trim().toLowerCase();if(!term)return STARTER;return STARTER.filter(x=>[x.code,x.name,x.category,x.subcategory,x.description,...x.keywords].some(v=>v.toLowerCase().includes(term)))},[q]);return <View style={s.screen}><View style={s.header}><Pressable onPress={()=>nav.goBack()} style={s.btn}><Icon name="arrow-left" size={23} color="#111827"/></Pressable><Text style={s.title}>HS Code Finder</Text><View style={s.btn}/></View><View style={s.search}><Icon name="magnify" size={20} color="#64748B"/><TextInput value={q} onChangeText={setQ} placeholder="Search product name or keyword" placeholderTextColor="#94A3B8" style={s.input}/>{q?<Pressable onPress={()=>setQ('')}><Icon name="close-circle" size={19} color="#94A3B8"/></Pressable>:null}</View><ScrollView contentContainerStyle={s.content}>{results.length?results.map(x=><View key={x.code} style={s.card}><View style={s.codeRow}><Text style={s.code}>{x.code}</Text><Text style={s.category}>{x.category}</Text></View><Text style={s.name}>{x.name}</Text><Text style={s.sub}>{x.subcategory}</Text><Text style={s.desc}>{x.description}</Text><Text style={s.related}>Related HS codes: {x.related.join(' · ')}</Text><Pressable onPress={()=>nav.navigate('ProductListing',{q:x.name})} style={s.products}><Text style={s.productsText}>View related products</Text><Icon name="arrow-right" size={15} color="#2563EB"/></Pressable></View>):<View style={s.empty}><Icon name="barcode-off" size={42} color="#94A3B8"/><Text style={s.emptyTitle}>No matching HS code</Text><Text style={s.emptyText}>Try a broader product name, material or keyword.</Text></View>}</ScrollView></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8FAFC'},header:{paddingTop:48,paddingBottom:10,paddingHorizontal:12,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center'},btn:{width:42,height:42,alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',fontSize:17,fontWeight:'900',color:'#111827'},search:{height:48,margin:14,marginBottom:4,paddingHorizontal:14,borderRadius:14,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',flexDirection:'row',alignItems:'center',gap:9},input:{flex:1,fontSize:12,color:'#111827'},content:{padding:14,paddingBottom:60},card:{backgroundColor:'#FFF',borderRadius:15,padding:15,borderWidth:1,borderColor:'#E2E8F0',marginBottom:10},codeRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},code:{fontSize:15,fontWeight:'900',color:'#2563EB'},category:{fontSize:9,fontWeight:'800',color:'#475569',backgroundColor:'#F1F5F9',paddingHorizontal:8,paddingVertical:5,borderRadius:10},name:{fontSize:14,fontWeight:'900',color:'#0F172A',marginTop:10},sub:{fontSize:10,color:'#64748B',marginTop:3},desc:{fontSize:11,lineHeight:17,color:'#475569',marginTop:9},related:{fontSize:9,color:'#64748B',marginTop:10},products:{flexDirection:'row',alignItems:'center',gap:5,marginTop:12},productsText:{fontSize:10,fontWeight:'900',color:'#2563EB'},empty:{alignItems:'center',paddingTop:80},emptyTitle:{fontSize:15,fontWeight:'900',color:'#334155',marginTop:12},emptyText:{fontSize:11,color:'#64748B',marginTop:5}});
