import React from 'react';
import { Alert, Linking, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import { useQuery } from '@tanstack/react-query';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { fetchInvoices } from '../api/marketplace';
import { EmptyState, ErrorState, LoadingState } from '../components/StateViews';
import { useCurrency } from '../currency/CurrencyContext';
import { colors, radii, shadow, spacing } from '../theme';
import { getId } from '../utils/format';

function InvoiceDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const { invoiceId, orderId } = route.params as { invoiceId?: string; orderId?: string }; const { formatPrice } = useCurrency();
  const query = useQuery({ queryKey: ['invoices'], queryFn: fetchInvoices });
  if (query.isLoading) return <LoadingState label="Loading invoice" />;
  if (query.isError) return <ErrorState message={(query.error as Error)?.message ?? 'Invoices were not returned.'} onRetry={() => query.refetch()} />;
  const invoice = (query.data ?? []).find(item => (invoiceId && getId(item) === invoiceId) || (orderId && idOf(item.orderId) === orderId));
  if (!invoice) return <EmptyState title="Invoice not available" detail="The backend has not issued an invoice for this order yet." />;
  const currency = String(invoice.currency ?? 'INR'); const documentUrl = typeof invoice.documentUrl === 'string' ? invoice.documentUrl : undefined; const lines = Array.isArray(invoice.lineItems) ? invoice.lineItems as Record<string, unknown>[] : [];
  const openDocument = async () => { if (!documentUrl) return Alert.alert('Document pending', 'The invoice document has not been generated yet.'); await Linking.openURL(documentUrl); };
  return <View style={styles.screen}><View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.iconButton}><Icon name="arrow-left" size={24} color={colors.ink} /></Pressable><Text style={styles.headerTitle}>Invoice</Text><View style={styles.iconButton} /></View><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.paper}><View style={styles.invoiceTop}><View><Text style={styles.brand}>ESYGLOB</Text><Text style={styles.invoiceNumber}>{String(invoice.invoiceNumber ?? 'Invoice')}</Text></View><Text style={styles.status}>{String(invoice.status ?? 'draft')}</Text></View>
      <View style={styles.parties}><Party title="Bill to" data={invoice.buyerSnapshot} /><Party title="Supplier" data={invoice.sellerSnapshot} /></View>
      <Row label="Order number" value={read(invoice.orderId, 'orderNumber')} /><Row label="Issued" value={date(invoice.issuedAt)} /><Row label="Due" value={date(invoice.dueAt)} /><Row label="Payment status" value={invoice.paymentStatus} />
      <Text style={styles.sectionTitle}>Line items</Text>{lines.map((line, index) => <View key={index} style={styles.line}><View style={styles.lineBody}><Text style={styles.lineTitle}>{String(line.description ?? `Item ${index + 1}`)}</Text><Text style={styles.lineMeta}>{String(line.quantity ?? 1)} {String(line.unit ?? '')} × {formatPrice(Number(line.unitPrice ?? 0), currency)}</Text></View><Text style={styles.lineTotal}>{formatPrice(Number(line.total ?? 0), currency)}</Text></View>)}
      <View style={styles.totals}><Row label="Subtotal" value={formatPrice(Number(invoice.subtotal ?? 0), currency)} /><Row label="GST / Tax" value={formatPrice(Number(invoice.taxAmount ?? 0), currency)} /><Row label="Shipping" value={formatPrice(Number(invoice.shippingAmount ?? 0), currency)} /><Row label="Discount" value={formatPrice(Number(invoice.discountAmount ?? 0), currency)} /><Row label="Total" value={formatPrice(Number(invoice.totalAmount ?? 0), currency)} strong /></View>
      <Text style={styles.sectionTitle}>Shipment</Text><Snapshot data={invoice.shipmentSnapshot} />
    </View>
    <View style={styles.actions}><Pressable onPress={openDocument} style={styles.action}><Icon name="eye-outline" size={19} color="#fff" /><Text style={styles.actionText}>View</Text></Pressable><Pressable onPress={openDocument} style={styles.action}><Icon name="download-outline" size={19} color="#fff" /><Text style={styles.actionText}>Download</Text></Pressable><Pressable onPress={() => Share.share({ title: String(invoice.invoiceNumber ?? 'Invoice'), message: documentUrl ?? `Invoice ${String(invoice.invoiceNumber ?? '')}` })} style={styles.action}><Icon name="share-variant-outline" size={19} color="#fff" /><Text style={styles.actionText}>Share</Text></Pressable></View>
  </ScrollView></View>;
}
function Party({ title, data }: { title: string; data: unknown }) { const item = record(data); return <View style={styles.party}><Text style={styles.partyTitle}>{title}</Text><Text style={styles.partyName}>{String(item?.companyName ?? item?.fullName ?? item?.name ?? 'Pending')}</Text><Text style={styles.partyMeta}>{[item?.address, item?.email, item?.gstNumber].filter(Boolean).map(String).join('\n')}</Text></View>; }
function Snapshot({ data }: { data: unknown }) { const item = record(data); if (!item) return <Text style={styles.partyMeta}>Shipment details pending</Text>; return <View>{Object.entries(item).slice(0, 8).map(([key, value]) => <Row key={key} label={key.replace(/([A-Z])/g, ' $1')} value={typeof value === 'object' ? JSON.stringify(value) : value} />)}</View>; }
function Row({ label, value, strong }: { label: string; value: unknown; strong?: boolean }) { if (value === undefined || value === null || value === '') return null; return <View style={styles.row}><Text style={[styles.label, strong && styles.strong]}>{label}</Text><Text style={[styles.value, strong && styles.strong]}>{String(value).replace(/_/g, ' ')}</Text></View>; }
function record(value: unknown) { return value && typeof value === 'object' ? value as Record<string, unknown> : null; } function read(value: unknown, key: string) { return record(value)?.[key]; } function idOf(value: unknown) { return typeof value === 'string' ? value : String(read(value, '_id') ?? read(value, 'id') ?? ''); } function date(value: unknown) { return value ? new Date(String(value)).toLocaleDateString() : undefined; }
const styles = StyleSheet.create({ screen: { backgroundColor: colors.background, flex: 1 }, header: { alignItems: 'center', backgroundColor: colors.card, flexDirection: 'row', paddingHorizontal: spacing.md, paddingTop: spacing.xxl, paddingBottom: spacing.sm }, iconButton: { alignItems: 'center', height: 42, justifyContent: 'center', width: 42 }, headerTitle: { color: colors.ink, flex: 1, fontSize: 18, fontWeight: '900', textAlign: 'center' }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, paper: { backgroundColor: colors.card, borderRadius: radii.md, padding: spacing.xl, ...shadow }, invoiceTop: { alignItems: 'flex-start', borderBottomColor: colors.faint, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingBottom: spacing.lg }, brand: { color: colors.primary, fontSize: 22, fontWeight: '900' }, invoiceNumber: { color: colors.muted, fontSize: 12, marginTop: 4 }, status: { backgroundColor: '#fff8f3', borderRadius: radii.pill, color: colors.primaryDark, fontSize: 11, fontWeight: '900', paddingHorizontal: spacing.md, paddingVertical: spacing.xs, textTransform: 'uppercase' }, parties: { flexDirection: 'row', gap: spacing.lg, marginVertical: spacing.lg }, party: { flex: 1 }, partyTitle: { color: colors.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' }, partyName: { color: colors.ink, fontSize: 14, fontWeight: '900', marginTop: 5 }, partyMeta: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, sectionTitle: { color: colors.ink, fontSize: 14, fontWeight: '900', marginTop: spacing.lg, marginBottom: spacing.sm }, row: { borderBottomColor: colors.faint, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.sm }, label: { color: colors.muted, flex: 1, fontSize: 12, fontWeight: '700', textTransform: 'capitalize' }, value: { color: colors.ink, flex: 1, fontSize: 12, fontWeight: '800', textAlign: 'right', textTransform: 'capitalize' }, strong: { color: colors.ink, fontSize: 15, fontWeight: '900' }, line: { alignItems: 'center', borderBottomColor: colors.faint, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', paddingVertical: spacing.sm }, lineBody: { flex: 1 }, lineTitle: { color: colors.ink, fontSize: 12, fontWeight: '800' }, lineMeta: { color: colors.muted, fontSize: 10, marginTop: 3 }, lineTotal: { color: colors.ink, fontSize: 12, fontWeight: '900' }, totals: { marginLeft: '28%', marginTop: spacing.md }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg }, action: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radii.pill, flex: 1, flexDirection: 'row', gap: 5, justifyContent: 'center', padding: spacing.md }, actionText: { color: '#fff', fontSize: 12, fontWeight: '900' } });
export default InvoiceDetailsScreen;
