import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { ServiceRequest } from '../api/services';

export default function ServiceBookingSuccessScreen() {
  const navigation = useNavigation<any>();
  const request = (useRoute<any>().params?.request ?? {}) as ServiceRequest;
  const invoiceId = typeof request.invoiceId === 'object' ? String((request.invoiceId as any)._id ?? '') : String(request.invoiceId ?? '');
  return <View style={s.screen}><View style={s.content}><View style={s.check}><Icon name="check" size={38} color="#fff" /></View><Text style={s.title}>Booking confirmed</Text><Text style={s.subtitle}>Your payment was verified and the service team has received your request.</Text><View style={s.card}><Row label="Service" value={request.serviceTitle} /><Row label="Booking ID" value={request.requestNumber ?? request._id} /><Row label="Payment" value={request.paymentStatus ?? 'paid'} /><Row label="Status" value={request.status ?? 'under review'} /></View><Text style={s.note}>Your invoice and every future status update are synchronized with your service dashboard.</Text></View><View style={s.actions}>{invoiceId ? <Pressable onPress={() => navigation.navigate('InvoiceDetails', { invoiceId })} style={s.secondary}><Icon name="file-pdf-box" size={19} color="#2563EB" /><Text style={s.secondaryText}>View invoice</Text></Pressable> : null}<Pressable onPress={() => navigation.replace('Tracking', { request })} style={s.primary}><Text style={s.primaryText}>Track service</Text><Icon name="arrow-right" size={18} color="#fff" /></Pressable></View></View>;
}
function Row({ label, value }: { label: string; value: unknown }) { return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{String(value ?? '-').replace(/_/g, ' ')}</Text></View>; }
const s = StyleSheet.create({ screen: { backgroundColor: '#F8FAFC', flex: 1 }, content: { alignItems: 'center', flex: 1, justifyContent: 'center', padding: 24 }, check: { alignItems: 'center', backgroundColor: '#16A34A', borderRadius: 38, height: 76, justifyContent: 'center', width: 76 }, title: { color: '#0F172A', fontSize: 25, fontWeight: '900', marginTop: 22 }, subtitle: { color: '#64748B', fontSize: 13, lineHeight: 20, marginTop: 8, maxWidth: 330, textAlign: 'center' }, card: { backgroundColor: '#fff', borderColor: '#E2E8F0', borderRadius: 16, borderWidth: 1, marginTop: 25, padding: 16, width: '100%' }, row: { borderBottomColor: '#F1F5F9', borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10 }, label: { color: '#64748B', fontSize: 12, fontWeight: '700' }, value: { color: '#0F172A', fontSize: 12, fontWeight: '900', textTransform: 'capitalize' }, note: { color: '#64748B', fontSize: 11, lineHeight: 17, marginTop: 16, textAlign: 'center' }, actions: { backgroundColor: '#fff', borderTopColor: '#E2E8F0', borderTopWidth: 1, flexDirection: 'row', gap: 10, padding: 16 }, secondary: { alignItems: 'center', borderColor: '#BFDBFE', borderRadius: 13, borderWidth: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 50, paddingHorizontal: 15 }, secondaryText: { color: '#2563EB', fontSize: 12, fontWeight: '900' }, primary: { alignItems: 'center', backgroundColor: '#2563EB', borderRadius: 13, flex: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 50 }, primaryText: { color: '#fff', fontSize: 13, fontWeight: '900' } });
