/* eslint-disable react-refresh/only-export-components, react-hooks/set-state-in-effect */
import { AlertTriangle, Check, Coins, LockKeyhole, Sparkles, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { createAICreditOrder, fetchAICreditPackages, fetchSubscription, verifyAICreditPayment } from '../api/verification'
import { Money } from './TradeUI'

const CREDIT_EVENT = 'esyglob:ai-credits-updated'
export function publishAICredits(credits) { if (credits) window.dispatchEvent(new CustomEvent(CREDIT_EVENT, { detail: credits })) }

export function useAICredits(role = 'buyer') {
  const [credits, setCredits] = useState(null); const [loading, setLoading] = useState(true)
  const refresh = useCallback(async () => { const data = await fetchSubscription(role); setCredits(data?.credits || { allocated: Number(data?.plan?.aiCredits?.monthly ?? data?.plan?.aiCredits ?? 0), used: Number(data?.usage?.aiCreditsUsed || 0), remaining: Number(data?.usage?.aiCreditsRemaining || 0), todayUsed: Number(data?.usage?.aiCreditsToday || 0), resetAt: data?.subscription?.creditsResetAt || data?.subscription?.usageResetAt }); setLoading(false); return data }, [role])
  const apply = useCallback(next => { if (!next) return; setCredits(current => { const usedDelta = Math.max(0, Number(next.used || 0) - Number(current?.used || 0)); return { ...current, ...next, todayUsed: next.todayUsed ?? Number(current?.todayUsed || 0) + usedDelta } }); publishAICredits(next) }, [])
  useEffect(() => { let live = true; refresh().catch(() => { if (live) setLoading(false) }); const receive = event => { if (live && event.detail) setCredits(current => ({ ...current, ...event.detail })) }; const refetch = () => { if (document.visibilityState === 'visible') refresh().catch(() => undefined) }; window.addEventListener(CREDIT_EVENT, receive); window.addEventListener('focus', refetch); document.addEventListener('visibilitychange', refetch); const timer = window.setInterval(refetch, 60_000); return () => { live = false; window.removeEventListener(CREDIT_EVENT, receive); window.removeEventListener('focus', refetch); document.removeEventListener('visibilitychange', refetch); window.clearInterval(timer) } }, [refresh])
  return { credits, loading, refresh, apply, exhausted: Boolean(credits && Number(credits.remaining) <= 0) }
}

export function AICreditMeter({ state, role = 'buyer', compact = false, className = '' }) {
  const source = state || { credits: null, loading: true }; const [dialogOpen, setDialogOpen] = useState(false); const credits = source.credits
  const allocated = Math.max(0, Number(credits?.allocated || 0)); const remaining = Math.max(0, Number(credits?.remaining || 0)); const used = Math.max(0, Number(credits?.used || 0)); const percentage = allocated ? Math.min(100, Math.round((used / allocated) * 100)) : 100; const low = allocated > 0 && remaining / allocated <= .2
  if (source.loading && !credits) return <div className={`ai-credit-meter is-loading ${className}`} aria-label="Loading AI credits" />
  return <><section className={`ai-credit-meter ${compact ? 'is-compact' : ''} ${low ? 'is-low' : ''} ${remaining <= 0 ? 'is-empty' : ''} ${className}`} aria-label="AI credit balance"><div className="ai-credit-meter__heading"><span><Coins /><small>AI credits</small><b>{remaining.toLocaleString()} available</b></span>{!compact && <button type="button" onClick={() => setDialogOpen(true)}>Buy credits</button>}</div><div className="ai-credit-meter__track"><i style={{ width: `${percentage}%` }} /></div>{!compact && <div className="ai-credit-meter__stats"><span><small>Included with plan</small><b>{Number(credits?.included ?? allocated).toLocaleString()}</b></span><span><small>Purchased</small><b>{Number(credits?.purchased || 0).toLocaleString()}</b></span><span><small>Consumed</small><b>{used.toLocaleString()}</b></span></div>}{compact && low && <button type="button" className="ai-credit-meter__upgrade" onClick={() => setDialogOpen(true)}>{remaining ? 'Running low' : 'Buy credits'}</button>}{!compact && low && <p><AlertTriangle /> {remaining ? `Only ${remaining} credits remain. Add credits without changing your subscription.` : 'Your AI credits are exhausted. Buy additional credits to continue.'}</p>}</section><AICreditDialog open={dialogOpen} onClose={() => setDialogOpen(false)} role={role} credits={credits} onPurchased={source.refresh} /></>
}

export function AICreditDialog({ open, onClose, credits, onPurchased }) {
  const [packages, setPackages] = useState([]); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { if (!open || packages.length) return; setLoading(true); fetchAICreditPackages().then(data => setPackages(data?.packages || [])).catch(error => setMessage(error.message)).finally(() => setLoading(false)) }, [open, packages.length])
  async function purchase(item) { setBusy(item.key); setMessage(''); try { await loadCheckout(); const order = await createAICreditOrder(item.key); await new Promise((resolve, reject) => { const checkout = new window.Razorpay({ key: order.key, amount: order.amount, currency: order.currency, name: 'EsyGlob', description: `${item.name} AI credits`, order_id: order.orderId, prefill: order.user, handler: async response => { try { const result = await verifyAICreditPayment({ razorpayPaymentId: response.razorpay_payment_id, razorpayOrderId: response.razorpay_order_id, razorpaySignature: response.razorpay_signature }); publishAICredits(result.credits); await onPurchased?.(); resolve(result) } catch (error) { reject(error) } }, modal: { ondismiss: () => reject(new Error('Payment cancelled. No credits were added.')) } }); checkout.on('payment.failed', event => reject(new Error(event.error?.description || 'Payment failed. No credits were added.'))); checkout.open() }); setMessage('Credits added successfully 🎉 Your AI credits were added to your current plan.') } catch (error) { setMessage(error.message) } finally { setBusy('') } }
  if (!open) return null
  return <div className="ai-credit-dialog" role="dialog" aria-modal="true" aria-labelledby="ai-credit-dialog-title"><button className="ai-credit-dialog__backdrop" aria-label="Close credit packages" onClick={onClose} /><section><header><i><Sparkles /></i><div><span>Additional AI credits</span><h2 id="ai-credit-dialog-title">Buy credits</h2><p>Your subscription stays unchanged. Current balance: <b>{Number(credits?.remaining || 0)} credits</b>.</p></div><button type="button" aria-label="Close" onClick={onClose}><X /></button></header><div className="ai-credit-dialog__trust"><span><LockKeyhole /> Secure payment</span><span><Check /> Backend-verified balance</span><span><Check /> Current plan stays active</span></div><div className="ai-credit-dialog__plans">{loading ? <p>Loading credit packages…</p> : packages.length ? packages.map(item => <article className={item.popular ? 'recommended' : ''} key={item.key}><span>{item.popular ? 'Popular' : 'Credit pack'}</span><h3>{item.name}</h3><strong>{item.credits.toLocaleString()} <small>credits</small></strong><p><Money value={item.price} currency={item.currency} /></p><button className="button button--primary" disabled={Boolean(busy)} onClick={() => purchase(item)}>{busy === item.key ? 'Opening checkout…' : 'Buy credits'}</button></article>) : <p>No credit packages are currently configured.</p>}</div>{message && <p className={message.startsWith('Credits added') ? 'action-success' : 'action-error'}>{message}</p>}<footer><button type="button" className="button button--ghost" onClick={onClose}>Close</button></footer></section></div>
}

function loadCheckout() { if (window.Razorpay) return Promise.resolve(); return new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.async = true; script.onload = resolve; script.onerror = () => reject(new Error('Secure checkout could not be loaded.')); document.head.appendChild(script) }) }
