export const TRUSTED_PARTNERS = {
  asc: { name: 'ASC', logo: '/asc.png' },
  'maersk-warehousing': { name: 'Maersk Warehousing', logo: '/maersk-warehousing.webp' },
  'db-schenker': { name: 'DB Schenker', logo: '/db-schenker.webp' },
  'cj-darcl': { name: 'CJ Darcl Logistics', logo: '/cj-darcl.webp' },
  'dhl-express': { name: 'DHL Express', logo: '/dhl.webp' },
  fedex: { name: 'FedEx', logo: '/fedx.png' },
  delhivery: { name: 'Delhivery', logo: '/delhivery.png' },
  shiprocket: { name: 'Shiprocket', logo: '/shiprocket.png' },
  xpressbees: { name: 'Xpressbees', logo: '/xpressbees.png' },
  msc: { name: 'MSC', logo: '/msc.png' },
  'cma-cgm': { name: 'CMA CGM', logo: '/cma-cgm.webp' },
  'dhl-customs': { name: 'DHL Customs Services', logo: '/dhl.webp' },
  'fedex-customs': { name: 'FedEx Customs', logo: '/fedx.png' },
  'maersk-customs': { name: 'Maersk Customs Services', logo: '/maersk-warehousing.png' },
  'db-schenker-customs': { name: 'DB Schenker Customs', logo: '/db-schenker.png' },
  sgs: { name: 'SGS', logo: '/sgs.jpg' },
  'bureau-veritas': { name: 'Bureau Veritas', logo: '/bureau-veritas.png' },
  'tuv-rheinland': { name: 'TÜV Rheinland', logo: '/tuv-rheinland.png' },
  cotecna: { name: 'Cotecna', logo: '/cotecna.png' },
  qima: { name: 'QIMA', logo: '/qima.png' },
  'ul-solutions': { name: 'UL Solutions', logo: '/ul-solutions.png' },
  ce: { name: 'CE', logo: '/ce.png' },
  iso: { name: 'ISO', logo: '/iso.webp' },
  stripe: { name: 'Stripe', logo: '/stripe.png' },
  razorpay: { name: 'Razorpay', logo: '/razorpay.png' },
  paypal: { name: 'PayPal', logo: '/paypal.webp' },
  'wise-business': { name: 'Wise Business', logo: '/wise-business.webp' },
  mastercard: { name: 'Mastercard', logo: '/mastercard.jpg' },
  'stripe-connect': { name: 'Stripe Connect', logo: '/stripe-connect.png' },
  razorpayx: { name: 'RazorpayX', logo: '/razorpayx.png' },
  'escrow-com': { name: 'Escrow.com', logo: '/escrow-com.png' },
  castler: { name: 'Castler', logo: '/castler.png' },
  tazapay: { name: 'Tazapay', logo: '/tazapay.png' },
  transpact: { name: 'Transpact', logo: '/transpact.png' },
  trustap: { name: 'Trustap', logo: '/trustap.png' },
  'allianz-trade': { name: 'Allianz Trade', logo: '/allianz-trade.png' },
  'icici-lombard': { name: 'ICICI Lombard', logo: '/icici-lombard.png' },
  'tata-aig': { name: 'Tata AIG', logo: '/tata-aig.png' },
  'new-india-assurance': { name: 'New India Assurance', logo: '/new-india-assurance.png' },
  aig: { name: 'AIG', logo: '/aig.png' },
  coface: { name: 'Coface', logo: '/coface.png' },
  atradius: { name: 'Atradius', logo: '/atradius.png' },
  ecgc: { name: 'ECGC', logo: '/ecgc.png' },
  credendo: { name: 'Credendo', logo: '/credendo.png' },
  chubb: { name: 'Chubb', logo: '/chubb.png' },
  zurich: { name: 'Zurich Insurance', logo: '/zurich.png' },
  'tokio-marine': { name: 'Tokio Marine', logo: '/tokio-marine.png' },
  deloitte: { name: 'Deloitte', logo: '/deloitte.png' },
  pwc: { name: 'PwC', logo: '/pwc.png' },
  ey: { name: 'EY', logo: '/ey.png' },
  kpmg: { name: 'KPMG', logo: '/kpmg.png' },
  accenture: { name: 'Accenture', logo: '/accenture.png' },
  mckinsey: { name: 'McKinsey & Company', logo: '/mckinsey.png' },
  bcg: { name: 'BCG', logo: '/bcg.png' },
  bain: { name: 'Bain & Company', logo: '/bain.png' },
  icc: { name: 'ICC Dispute Resolution', logo: '/icc.png' },
  siac: { name: 'SIAC', logo: '/siac.png' },
  lcia: { name: 'LCIA', logo: '/lcia.png' },
  icdr: { name: 'ICDR', logo: '/icdr.png' },
  mcia: { name: 'MCIA', logo: '/mcia.png' },
  'dun-bradstreet': { name: 'Dun & Bradstreet', logo: '/dun-bradstreet.png' },
  crif: { name: 'CRIF', logo: '/crif.png' },
  'experian-business': { name: 'Experian Business', logo: '/experian-business.png' },
  creditsafe: { name: 'Creditsafe', logo: '/creditsafe.png' },
  equifax: { name: 'Equifax', logo: '/equifax.png' },
  moodys: { name: "Moody's", logo: '/moodys.png' },
  dgft: { name: 'DGFT', logo: '/dgft.png' },
  fieo: { name: 'FIEO', logo: '/fieo.png' },
  apeda: { name: 'APEDA', logo: '/apeda.png' },
  'epc-india': { name: 'EPC India', logo: '/epc-india.png' },
}

export const SERVICE_TRUSTED_PARTNERS = {
  warehousing: ['asc', 'dhl-supply-chain', 'maersk-warehousing', 'db-schenker', 'cj-darcl', 'delhivery-warehousing'],
  shipping: ['dhl-express', 'fedex', 'ups', 'blue-dart', 'delhivery', 'shiprocket', 'xpressbees', 'maersk'],
  'customs-brokerage': ['dhl-customs', 'fedex-customs', 'ups-brokerage', 'maersk-customs', 'kuehne-nagel-customs', 'db-schenker-customs'],
  'quality-inspection': ['sgs', 'bureau-veritas', 'intertek', 'tuv-sud', 'tuv-rheinland', 'cotecna', 'qima'],
  'product-testing': ['ul-solutions', 'tuv-sud', 'tuv-rheinland', 'sgs', 'bureau-veritas', 'intertek', 'ce', 'bis'],
  'trade-financing': ['mastercard', 'wise-business', 'stripe', 'axis-bank', 'sbi', 'citi', 'jpmorgan', 'standard-chartered'],
  escrow: ['escrow-com', 'castler', 'tazapay', 'transpact', 'trustap'],
  insurance: ['icici-lombard', 'tata-aig', 'new-india-assurance', 'aig', 'chubb', 'zurich', 'tokio-marine'],
  consulting: ['deloitte', 'pwc', 'ey', 'kpmg', 'accenture', 'mckinsey', 'bcg', 'bain'],
  'seller-verification': ['dun-bradstreet', 'crif', 'experian-business', 'creditsafe', 'equifax', 'moodys'],
  'dispute-resolution': ['icc', 'siac', 'lcia', 'icdr', 'mcia'],
  compliance: ['dgft', 'icegate', 'cbic', 'fieo', 'apeda', 'epc-india'],
  'quality-assurance': ['sgs', 'bureau-veritas', 'intertek', 'tuv-sud', 'tuv-rheinland', 'qima'],
  'global-trade-support': ['dhl-express', 'maersk', 'ups', 'fedex', 'wise-business', 'stripe'],
}

export function partnersForService(serviceKey) {
  return (SERVICE_TRUSTED_PARTNERS[serviceKey] || [])
    .map(key => ({ key, ...TRUSTED_PARTNERS[key] }))
    .filter(partner => partner.logo)
}
