/* eslint-disable @typescript-eslint/no-shadow, react-native/no-inline-styles */
import React, { memo, useEffect, useMemo, useState } from 'react';
import { Text, View } from 'react-native';
import { CURRENCIES, CurrencyCode, useCurrency } from '../../currency/CurrencyContext';
import { FieldRow, NumberField, Option, ResultCard, SectionCard, SelectField } from './CalculatorUI';
import { CostSummary, numberValue as n, percentOf, safeDivide } from './calculations';

const currencyOptions: Option[] = CURRENCIES.map(value => ({ value, label: value }));
const gstOptions: Option[] = ['5','12','18','28','custom'].map(value => ({ value, label: value === 'custom' ? 'Custom rate' : `${value}% GST` }));
const countries: Option[] = ['India','China','United States','United Arab Emirates','United Kingdom','Germany','Singapore','Vietnam','Bangladesh','Indonesia','Japan','Australia','Canada','Other'].map(value => ({ value, label: value }));
const incoterms: Option[] = ['EXW','FOB','CIF','CFR','DAP','DDP'].map(value => ({ value, label: value }));
const money = (amount: number, currency: string) => {
  try { return new Intl.NumberFormat(currency === 'INR' ? 'en-IN' : 'en-US', { style: 'currency', currency, maximumFractionDigits: currency === 'INR' ? 0 : 2 }).format(amount); }
  catch { return `${currency} ${amount.toFixed(2)}`; }
};

type SummaryProps = { onSummaryChange: (summary: CostSummary) => void };

export const LandedCostCalculator = memo(function LandedCostModule({ onSummaryChange }: SummaryProps) {
  const { formatPrice, selectedCurrency } = useCurrency(); const [currency,setCurrency]=useState<CurrencyCode>(selectedCurrency); const [incoterm,setIncoterm]=useState('FOB');
  const [v,setV]=useState({product:'',moq:'',quantity:'',freight:'',insurance:'',packaging:'',handling:'',loading:'',port:'',duty:'',gst:'18',platform:'',other:'',rate:'1',margin:''});
  const set=(key:keyof typeof v)=>(value:string)=>setV(current=>({...current,[key]:value}));
  const r=useMemo(()=>{const quantity=n(v.quantity)||n(v.moq);const product=n(v.product)*quantity*(n(v.rate)||1);const preDuty=product+n(v.freight)+n(v.insurance)+n(v.packaging)+n(v.handling)+n(v.loading)+n(v.port);const duty=percentOf(preDuty,v.duty);const gst=percentOf(preDuty+duty,v.gst);const platform=percentOf(product,v.platform);const total=preDuty+duty+gst+platform+n(v.other);const unit=safeDivide(total,quantity);const selling=n(v.margin)<100?unit/(1-n(v.margin)/100):unit;const summary={productCost:product,freight:n(v.freight),insurance:n(v.insurance),duty,gst,platformFee:platform,packaging:n(v.packaging),misc:n(v.handling)+n(v.loading)+n(v.port)+n(v.other),grandTotal:total,costPerUnit:unit};return{...summary,selling,gross:selling-unit};},[v]);
  useEffect(()=>{onSummaryChange({productCost:r.productCost,freight:r.freight,insurance:r.insurance,duty:r.duty,gst:r.gst,platformFee:r.platformFee,packaging:r.packaging,misc:r.misc,grandTotal:r.grandTotal,costPerUnit:r.costPerUnit});},[onSummaryChange,r]);
  return <><SectionCard title="Product & shipment" icon="package-variant-closed"><FieldRow><NumberField label="Unit product cost" value={v.product} onChange={set('product')} suffix={currency}/><NumberField label="Quantity" value={v.quantity} onChange={set('quantity')} suffix="units"/></FieldRow><FieldRow><NumberField label="MOQ" value={v.moq} onChange={set('moq')} suffix="units"/><SelectField label="Currency" value={currency} options={currencyOptions} onChange={x=>setCurrency(x as CurrencyCode)}/></FieldRow><FieldRow><SelectField label="Incoterm" value={incoterm} options={incoterms} onChange={setIncoterm}/><NumberField label="Exchange rate" value={v.rate} onChange={set('rate')} hint={`1 ${currency} in settlement currency`}/></FieldRow></SectionCard><SectionCard title="Logistics & charges" icon="truck-cargo-container"><FieldRow><NumberField label="Freight" value={v.freight} onChange={set('freight')}/><NumberField label="Insurance" value={v.insurance} onChange={set('insurance')}/></FieldRow><FieldRow><NumberField label="Packaging" value={v.packaging} onChange={set('packaging')}/><NumberField label="Handling" value={v.handling} onChange={set('handling')}/></FieldRow><FieldRow><NumberField label="Loading" value={v.loading} onChange={set('loading')}/><NumberField label="Port charges" value={v.port} onChange={set('port')}/></FieldRow><NumberField label="Other charges" value={v.other} onChange={set('other')}/></SectionCard><SectionCard title="Taxes, fee & margin" icon="percent-outline"><FieldRow><NumberField label="Duty" value={v.duty} onChange={set('duty')} suffix="%"/><NumberField label="GST / Tax" value={v.gst} onChange={set('gst')} suffix="%"/></FieldRow><FieldRow><NumberField label="Platform fee" value={v.platform} onChange={set('platform')} suffix="%"/><NumberField label="Target gross margin" value={v.margin} onChange={set('margin')} suffix="%"/></FieldRow></SectionCard><ResultCard title="Total landed cost" value={formatPrice(r.grandTotal,currency)} rows={[{label:'Product cost',value:formatPrice(r.productCost,currency)},{label:'Duty + GST',value:formatPrice(r.duty+r.gst,currency)},{label:'Cost per unit',value:formatPrice(r.costPerUnit,currency)},{label:'Estimated selling price',value:formatPrice(r.selling,currency),tone:'positive'},{label:'Gross margin per unit',value:formatPrice(r.gross,currency),tone:'positive'}]} note="Customs values are estimates. Confirm HS code, origin rules and assessable value with a licensed customs professional."/></>;
});

export const GstCalculator = memo(function GstCalculator(){const{formatPrice}=useCurrency();const[amount,setAmount]=useState('');const[mode,setMode]=useState('exclusive');const[rate,setRate]=useState('18');const[custom,setCustom]=useState('');const taxRate=rate==='custom'?n(custom):n(rate);const r=useMemo(()=>{const value=n(amount);if(mode==='inclusive'){const net=value/(1+taxRate/100);return{net,gst:value-net,gross:value};}const gst=percentOf(value,taxRate);return{net:value,gst,gross:value+gst};},[amount,mode,taxRate]);return <><SectionCard title="GST calculation" icon="receipt-text-outline"><SelectField label="Tax treatment" value={mode} options={[{label:'Exclusive GST',value:'exclusive'},{label:'Inclusive GST',value:'inclusive'}]} onChange={setMode}/><FieldRow><NumberField label={mode==='inclusive'?'Gross amount':'Net amount'} value={amount} onChange={setAmount}/><SelectField label="GST rate" value={rate} options={gstOptions} onChange={setRate}/></FieldRow>{rate==='custom'?<NumberField label="Custom GST rate" value={custom} onChange={setCustom} suffix="%"/>:null}</SectionCard><ResultCard title="Gross amount" value={formatPrice(r.gross,'INR')} rows={[{label:'Net amount',value:formatPrice(r.net,'INR')},{label:`GST (${taxRate}%)`,value:formatPrice(r.gst,'INR')},{label:'Gross amount',value:formatPrice(r.gross,'INR')}]} /></>});

export const ImportDutyCalculator = memo(function ImportDutyCalculator(){const{formatPrice}=useCurrency();const[v,setV]=useState({product:'',freight:'',insurance:'',bcd:'',sws:'10',igst:'18',other:''});const set=(k:keyof typeof v)=>(x:string)=>setV(c=>({...c,[k]:x}));const r=useMemo(()=>{const assessable=n(v.product)+n(v.freight)+n(v.insurance);const bcd=percentOf(assessable,v.bcd);const sws=percentOf(bcd,v.sws);const igst=percentOf(assessable+bcd+sws,v.igst);const other=percentOf(assessable,v.other);const duty=bcd+sws+igst+other;return{assessable,bcd,sws,igst,other,duty,total:assessable+duty};},[v]);return <><SectionCard title="Customs value" icon="ferry"><NumberField label="Product value" value={v.product} onChange={set('product')}/><FieldRow><NumberField label="Freight" value={v.freight} onChange={set('freight')}/><NumberField label="Insurance" value={v.insurance} onChange={set('insurance')}/></FieldRow></SectionCard><SectionCard title="Duty rates" icon="bank-outline"><FieldRow><NumberField label="BCD" value={v.bcd} onChange={set('bcd')} suffix="%"/><NumberField label="SWS on BCD" value={v.sws} onChange={set('sws')} suffix="%"/></FieldRow><FieldRow><NumberField label="IGST" value={v.igst} onChange={set('igst')} suffix="%"/><NumberField label="Other duties" value={v.other} onChange={set('other')} suffix="%"/></FieldRow></SectionCard><ResultCard title="Grand total" value={formatPrice(r.total,'INR')} tone="amber" rows={[{label:'Assessable value',value:formatPrice(r.assessable,'INR')},{label:'BCD',value:formatPrice(r.bcd,'INR')},{label:'SWS',value:formatPrice(r.sws,'INR')},{label:'IGST',value:formatPrice(r.igst,'INR')},{label:'Other duties',value:formatPrice(r.other,'INR')},{label:'Total customs duty',value:formatPrice(r.duty,'INR'),tone:'warning'}]} note="Rates vary by HS code, country of origin, exemptions and customs notifications."/></>});

export const FreightCalculator = memo(function FreightCalculator(){const{formatPrice}=useCurrency();const[mode,setMode]=useState('air');const[origin,setOrigin]=useState('India');const[destination,setDestination]=useState('United States');const[v,setV]=useState({weight:'',volume:'',cbm:'',rate:''});const set=(k:keyof typeof v)=>(x:string)=>setV(c=>({...c,[k]:x}));const r=useMemo(()=>{const cbm=n(v.cbm)||n(v.volume);const chargeable=mode==='air'||mode==='courier'?Math.max(n(v.weight),cbm*167):Math.max(n(v.weight)/1000,cbm);const defaults:Record<string,number>={air:5.5,sea:90,road:1.2,rail:.8,courier:8};const cost=chargeable*(n(v.rate)||defaults[mode]);const days:Record<string,string>={air:'3–7 days',sea:'20–45 days',road:'3–12 days',rail:'7–20 days',courier:'2–6 days'};return{chargeable,cost,transit:days[mode]};},[mode,v]);return <><SectionCard title="Shipment route" icon="map-marker-path"><SelectField label="Freight mode" value={mode} options={['air','sea','road','rail','courier'].map(x=>({label:x[0].toUpperCase()+x.slice(1),value:x}))} onChange={setMode}/><FieldRow><SelectField searchable label="Origin" value={origin} options={countries} onChange={setOrigin}/><SelectField searchable label="Destination" value={destination} options={countries} onChange={setDestination}/></FieldRow></SectionCard><SectionCard title="Cargo details" icon="weight-kilogram"><FieldRow><NumberField label="Weight" value={v.weight} onChange={set('weight')} suffix="kg"/><NumberField label="Volume" value={v.volume} onChange={set('volume')} suffix="m³"/></FieldRow><FieldRow><NumberField label="CBM" value={v.cbm} onChange={set('cbm')} suffix="m³"/><NumberField label="Rate (optional)" value={v.rate} onChange={set('rate')} suffix={mode==='air'||mode==='courier'?'/ kg':'/ unit'}/></FieldRow></SectionCard><ResultCard title="Estimated freight" value={formatPrice(r.cost,mode==='air'||mode==='courier'?'USD':'INR')} rows={[{label:'Route',value:`${origin} → ${destination}`},{label:'Chargeable measure',value:`${r.chargeable.toFixed(2)} ${mode==='air'||mode==='courier'?'kg':'W/M'}`},{label:'Estimated transit time',value:r.transit}]} note="Indicative only. Carrier, route, fuel surcharge, cargo class and seasonal capacity affect final quotes."/></>});

export const CurrencyCalculator = memo(function CurrencyCalculator(){const{exchangeRates,isLoading,error,refreshRates}=useCurrency();const[from,setFrom]=useState<CurrencyCode>('INR');const[to,setTo]=useState<CurrencyCode>('USD');const[amount,setAmount]=useState('');const value=useMemo(()=>n(amount)/(exchangeRates[from]||1)*(exchangeRates[to]||1),[amount,exchangeRates,from,to]);const rate=1/(exchangeRates[from]||1)*(exchangeRates[to]||1);return <><SectionCard title="Convert currency" icon="swap-horizontal"><FieldRow><SelectField label="From" value={from} options={currencyOptions} onChange={x=>setFrom(x as CurrencyCode)}/><SelectField label="To" value={to} options={currencyOptions} onChange={x=>setTo(x as CurrencyCode)}/></FieldRow><NumberField label="Amount" value={amount} onChange={setAmount} suffix={from}/></SectionCard><ResultCard title="Converted amount" value={money(value,to)} rows={[{label:'Current exchange rate',value:`1 ${from} = ${rate.toFixed(6)} ${to}`},{label:'Rates status',value:isLoading?'Updating…':error?'Cached rates':'Updated within the last hour',tone:error?'warning':'positive'}]} note={error??'Rates are cached for one hour and refreshed by the existing global Currency Context.'}/><Text onPress={()=>refreshRates(true).catch(()=>undefined)} style={{textAlign:'center',color:'#4F46E5',fontWeight:'800',fontSize:12,marginBottom:12}}>Refresh exchange rates</Text></>});

export const ProfitCalculator = memo(function ProfitCalculator(){const{formatPrice}=useCurrency();const[v,setV]=useState({buy:'',sell:'',quantity:'',expenses:'',platform:'',gst:'',shipping:''});const set=(k:keyof typeof v)=>(x:string)=>setV(c=>({...c,[k]:x}));const r=useMemo(()=>{const revenue=n(v.sell)*n(v.quantity);const buying=n(v.buy)*n(v.quantity);const platform=percentOf(revenue,v.platform);const gst=percentOf(revenue,v.gst);const costs=buying+n(v.expenses)+n(v.shipping)+platform+gst;const profit=revenue-costs;return{revenue,costs,profit,profitPct:safeDivide(profit,costs)*100,margin:safeDivide(profit,revenue)*100};},[v]);return <><SectionCard title="Price & quantity" icon="chart-line"><FieldRow><NumberField label="Buying price" value={v.buy} onChange={set('buy')}/><NumberField label="Selling price" value={v.sell} onChange={set('sell')}/></FieldRow><NumberField label="Quantity" value={v.quantity} onChange={set('quantity')}/></SectionCard><SectionCard title="Costs" icon="cash-minus"><FieldRow><NumberField label="Expenses" value={v.expenses} onChange={set('expenses')}/><NumberField label="Shipping" value={v.shipping} onChange={set('shipping')}/></FieldRow><FieldRow><NumberField label="Platform fee" value={v.platform} onChange={set('platform')} suffix="%"/><NumberField label="GST" value={v.gst} onChange={set('gst')} suffix="%"/></FieldRow></SectionCard><ResultCard title="Net earnings" value={formatPrice(r.profit,'INR')} tone={r.profit>=0?'green':'amber'} rows={[{label:'Revenue',value:formatPrice(r.revenue,'INR')},{label:'Total costs',value:formatPrice(r.costs,'INR')},{label:'Profit %',value:`${r.profitPct.toFixed(2)}%`,tone:r.profit>=0?'positive':'warning'},{label:'Margin',value:`${r.margin.toFixed(2)}%`,tone:r.profit>=0?'positive':'warning'}]}/></>});

export const MoqCalculator = memo(function MoqCalculator(){const{formatPrice}=useCurrency();const[quantity,setQuantity]=useState('');const[tier1,setTier1]=useState({moq:'100',price:''});const[tier2,setTier2]=useState({moq:'500',price:''});const[tier3,setTier3]=useState({moq:'1000',price:''});const tiers=[tier1,tier2,tier3].map(x=>({moq:n(x.moq),price:n(x.price)})).filter(x=>x.moq>0).sort((a,b)=>a.moq-b.moq);const selected=[...tiers].reverse().find(x=>n(quantity)>=x.moq)??tiers[0]??{moq:0,price:0};const base=tiers[0]?.price||0;const order=n(quantity)*selected.price;const discount=Math.max(0,(base-selected.price)*n(quantity));return <><SectionCard title="MOQ price tiers" icon="format-list-numbered"><TierFields index={1} value={tier1} set={setTier1}/><TierFields index={2} value={tier2} set={setTier2}/><TierFields index={3} value={tier3} set={setTier3}/></SectionCard><SectionCard title="Buyer quantity" icon="cart-outline"><NumberField label="Order quantity" value={quantity} onChange={setQuantity} suffix="units"/></SectionCard><ResultCard title="Order value" value={formatPrice(order,'INR')} tone="green" rows={[{label:'Applied MOQ tier',value:selected.moq?`${selected.moq}+ units`:'—'},{label:'Final unit cost',value:formatPrice(selected.price,'INR')},{label:'Discount',value:formatPrice(discount,'INR'),tone:'positive'},{label:'Average cost',value:formatPrice(safeDivide(order,quantity),'INR')}]} /></>});
function TierFields({index,value,set}:{index:number;value:{moq:string;price:string};set:React.Dispatch<React.SetStateAction<{moq:string;price:string}>>}){return <FieldRow><NumberField label={`Tier ${index} MOQ`} value={value.moq} onChange={moq=>set(x=>({...x,moq}))} suffix="units"/><NumberField label={`Tier ${index} unit price`} value={value.price} onChange={price=>set(x=>({...x,price}))}/></FieldRow>}

export const PackagingCalculator = memo(function PackagingCalculator(){const[v,setV]=useState({length:'',width:'',height:'',weight:'',boxes:'1'});const[unit,setUnit]=useState('cm');const set=(k:keyof typeof v)=>(x:string)=>setV(c=>({...c,[k]:x}));const r=useMemo(()=>{const divisor=unit==='cm'?1_000_000:unit==='mm'?1_000_000_000:1;const boxVolume=n(v.length)*n(v.width)*n(v.height)/divisor;const cbm=boxVolume*n(v.boxes);const actual=n(v.weight)*n(v.boxes);const volumetric=cbm*167;return{boxVolume,cbm,actual,chargeable:Math.max(actual,volumetric)};},[unit,v]);return <><SectionCard title="Package dimensions" icon="cube-outline"><SelectField label="Dimension unit" value={unit} options={[{label:'Centimetres (cm)',value:'cm'},{label:'Millimetres (mm)',value:'mm'},{label:'Metres (m)',value:'m'}]} onChange={setUnit}/><FieldRow><NumberField label="Length" value={v.length} onChange={set('length')} suffix={unit}/><NumberField label="Width" value={v.width} onChange={set('width')} suffix={unit}/></FieldRow><FieldRow><NumberField label="Height" value={v.height} onChange={set('height')} suffix={unit}/><NumberField label="Weight / box" value={v.weight} onChange={set('weight')} suffix="kg"/></FieldRow><NumberField label="Number of boxes" value={v.boxes} onChange={set('boxes')} /></SectionCard><ResultCard title="Total packaging volume" value={`${r.cbm.toFixed(3)} CBM`} rows={[{label:'Volume per box',value:`${r.boxVolume.toFixed(4)} m³`},{label:'Actual weight',value:`${r.actual.toFixed(2)} kg`},{label:'Air chargeable weight',value:`${r.chargeable.toFixed(2)} kg`}]} note="Air volumetric weight uses 167 kg per CBM. Carrier divisors can vary."/></>});

export const TradeSummaryCalculator = memo(function TradeSummaryCalculator({ summary }: { summary: CostSummary }){const{formatPrice}=useCurrency();const[v,setV]=useState({product:String(summary.productCost||''),freight:String(summary.freight||''),insurance:String(summary.insurance||''),duty:String(summary.duty||''),gst:String(summary.gst||''),platform:String(summary.platformFee||''),packaging:String(summary.packaging||''),misc:String(summary.misc||''),quantity:''});const set=(k:keyof typeof v)=>(x:string)=>setV(c=>({...c,[k]:x}));const r=useMemo(()=>{const total=n(v.product)+n(v.freight)+n(v.insurance)+n(v.duty)+n(v.gst)+n(v.platform)+n(v.packaging)+n(v.misc);return{total,unit:safeDivide(total,v.quantity)}},[v]);return <><SectionCard title="Consolidated trade costs" icon="clipboard-text-outline"><FieldRow><NumberField label="Product cost" value={v.product} onChange={set('product')}/><NumberField label="Freight" value={v.freight} onChange={set('freight')}/></FieldRow><FieldRow><NumberField label="Insurance" value={v.insurance} onChange={set('insurance')}/><NumberField label="Duty" value={v.duty} onChange={set('duty')}/></FieldRow><FieldRow><NumberField label="GST" value={v.gst} onChange={set('gst')}/><NumberField label="Platform fee" value={v.platform} onChange={set('platform')}/></FieldRow><FieldRow><NumberField label="Packaging" value={v.packaging} onChange={set('packaging')}/><NumberField label="Misc charges" value={v.misc} onChange={set('misc')}/></FieldRow><NumberField label="Quantity" value={v.quantity} onChange={set('quantity')} suffix="units"/></SectionCard><ResultCard title="Grand total" value={formatPrice(r.total,'INR')} rows={[{label:'Product cost',value:formatPrice(n(v.product),'INR')},{label:'Logistics',value:formatPrice(n(v.freight)+n(v.insurance)+n(v.packaging),'INR')},{label:'Taxes & duty',value:formatPrice(n(v.duty)+n(v.gst),'INR')},{label:'Fees & misc',value:formatPrice(n(v.platform)+n(v.misc),'INR')},{label:'Cost per unit',value:formatPrice(r.unit,'INR'),tone:'positive'}]}/></>});

export const CalculatorIntro = ({ children }: { children: React.ReactNode }) => <View style={{marginBottom:12}}><Text style={{fontSize:12,lineHeight:18,color:'#64748B'}}>{children}</Text></View>;
