import SubscriptionPlan from '../models/SubscriptionPlan.js';

export const DEFAULT_PLANS = [
  // ==================== BUYER PLANS ====================
  {
    key: 'buyer_free',
    role: 'buyer',
    name: 'Free Buyer',
    description: 'For new buyers & small businesses starting their sourcing journey',
    prices: { monthly: 0, quarterly: 0, yearly: 0 },
    aiCredits: 1500,
    storageLimitMb: 200,
    supportLevel: 'standard',
    trustScoreBoost: 0,
    verificationLevel: 'basic',
    aiTier: 'esyai_lite',
    priorityRanking: 0,
    features: [
      'Unlimited Product Browsing',
      'Unlimited Seller Browsing',
      'Save Products & Sellers',
      'Basic RFQ Creation',
      'Standard Search Filters',
      'Basic AI Chat & Q&A',
      'Basic Product/Search Suggestions',
      'Basic Trade Calculator',
      'Basic Shipment Tracking',
      'Standard Support',
    ],
    limits: {
      aiRequests: 1500,
      rfqs: 30,
      quotations: 30,
      products: 0,
      messages: 200,
      serviceBookings: 20,
      marketInsights: 20,
      imageUploads: 50,
      documents: 100,
      savedProducts: 500,
      savedSellers: 200,
      wishlistItems: 300,
    },
  },
  {
    key: 'buyer_pro',
    role: 'buyer',
    name: 'Buyer Pro',
    description: 'Smart AI tools & priority access for serious buyers',
    prices: { monthly: 1499, quarterly: 3999, yearly: 14990 },
    aiCredits: 500,
    storageLimitMb: 2048,
    supportLevel: 'priority',
    trustScoreBoost: 5,
    verificationLevel: 'basic',
    aiTier: 'esyai_pro',
    priorityRanking: 1,
    features: [
      'Everything in Free Buyer',
      'Personalized AI Recommendations',
      'AI Price & MOQ Comparison',
      'AI RFQ Generator & Improver',
      'AI Smart Replies for Messages',
      'AI Market Insights (Advanced)',
      'Advanced Search Filters',
      'Priority RFQ Placement',
      'AI Recommended Sellers & Products',
      'Trade Assurance & Escrow Access',
      'Priority Support',
    ],
    limits: {
      aiRequests: 500,
      rfqs: 20,
      quotations: 30,
      products: 0,
      messages: 200,
      serviceBookings: 10,
      marketInsights: 20,
      imageUploads: 100,
      documents: 200,
      savedProducts: 500,
      savedSellers: 200,
      wishlistItems: -1,
    },
  },
  {
    key: 'buyer_business',
    role: 'buyer',
    name: 'Buyer Business',
    description: 'Advanced trade intelligence & AI business assistant for growing importers',
    prices: { monthly: 3999, quarterly: 10799, yearly: 39990 },
    aiCredits: 2000,
    storageLimitMb: 10240,
    supportLevel: 'priority',
    trustScoreBoost: 10,
    verificationLevel: 'business',
    aiTier: 'esyai_advanced',
    priorityRanking: 2,
    features: [
      'Everything in Buyer Pro',
      'AI Trade Consultant & Negotiation Assistant',
      'AI Import/Export Guide',
      'AI Customs & Compliance Checker',
      'AI Demand & Trend Forecasting',
      'Country Wise Trade Insights',
      'Import/Export Data Access',
      'Tariff & Duty Calculator',
      'HS Code Finder',
      'Multi-Team Access (Up to 5 Members)',
      'Shared RFQs & Wishlists',
      'Advanced Analytics Dashboard',
      'Dedicated Priority Support',
    ],
    limits: {
      aiRequests: 2000,
      rfqs: 100,
      quotations: 150,
      products: 0,
      messages: 1000,
      serviceBookings: 50,
      marketInsights: 100,
      imageUploads: 500,
      documents: 1000,
      savedProducts: -1,
      savedSellers: -1,
      wishlistItems: -1,
      teamMembers: 5,
    },
  },
  {
    key: 'buyer_enterprise',
    role: 'buyer',
    name: 'Buyer Enterprise',
    description: 'Full-scale enterprise procurement with personal AI trade consultant',
    prices: { monthly: 9999, quarterly: 26999, yearly: 99990 },
    aiCredits: 10000,
    storageLimitMb: 51200,
    supportLevel: 'dedicated',
    trustScoreBoost: 20,
    verificationLevel: 'enterprise',
    aiTier: 'esyai_enterprise',
    priorityRanking: 3,
    features: [
      'Everything in Buyer Business',
      'Personal AI Trade Consultant',
      'AI Daily Briefs & Weekly Reports',
      'AI Risk & Supply Chain Analysis',
      'AI Procurement & Profit Optimization',
      'API Access',
      'Dedicated Account Manager',
      'SLA Guaranteed Support',
      'Unlimited Team Workspace',
      'ERP Integration Ready',
    ],
    limits: {
      aiRequests: 10000,
      rfqs: -1,
      quotations: -1,
      products: 0,
      messages: -1,
      serviceBookings: -1,
      marketInsights: -1,
      imageUploads: -1,
      documents: -1,
      savedProducts: -1,
      savedSellers: -1,
      wishlistItems: -1,
      teamMembers: -1,
    },
  },

  // ==================== SELLER PLANS ====================
  {
    key: 'seller_free',
    role: 'seller',
    name: 'Free Seller',
    description: 'Start selling on EsyGlob with basic store & tools',
    prices: { monthly: 0, quarterly: 0, yearly: 0 },
    aiCredits: 1500,
    storageLimitMb: 200,
    supportLevel: 'standard',
    trustScoreBoost: 0,
    verificationLevel: 'basic',
    aiTier: 'esyai_lite',
    priorityRanking: 0,
    features: [
      'Basic Store Setup',
      'List up to 15 Products',
      'Basic RFQ Access & Messaging',
      'Basic Product Description Generator',
      'Basic AI Chat Q&A',
      'Email & Mobile Verification',
      'Standard Support',
    ],
    limits: {
      aiRequests: 1500,
      rfqs: 30,
      quotations: 30,
      products: 15,
      messages: 60,
      serviceBookings: 20,
      marketInsights: 20,
      imageUploads: 50,
      documents: 100,
    },
  },
  {
    key: 'seller_verified',
    role: 'seller',
    name: 'Verified Seller',
    description: 'Get verified, build trust & unlock growth tools',
    prices: { monthly: 2499, quarterly: 6749, yearly: 24990 },
    aiCredits: 500,
    storageLimitMb: 2048,
    supportLevel: 'priority',
    trustScoreBoost: 10,
    verificationLevel: 'business',
    aiTier: 'esyai_pro',
    priorityRanking: 1,
    features: [
      'Everything in Free Seller',
      'GST, PAN, Business & Bank Verification',
      'Verified Badge on Profile',
      'Higher Trust Score (+10)',
      'Advanced AI SEO Title & Keywords Generator',
      'AI Quotation Generator',
      'AI Product Improvement Suggestions',
      'Unlock up to 50 Products',
      'Better Search Rankings',
      'Priority RFQ Access',
      'Seller Analytics Dashboard',
      'Priority Support',
    ],
    limits: {
      aiRequests: 500,
      rfqs: 20,
      quotations: 30,
      products: 50,
      messages: 200,
      serviceBookings: 10,
      marketInsights: 20,
      imageUploads: 100,
      documents: 200,
    },
  },
  {
    key: 'seller_gold',
    role: 'seller',
    name: 'Gold Seller',
    description: 'Factory verified, priority ranking & AI-powered sales optimization',
    prices: { monthly: 5999, quarterly: 16199, yearly: 59990 },
    aiCredits: 2500,
    storageLimitMb: 10240,
    supportLevel: 'priority',
    trustScoreBoost: 20,
    verificationLevel: 'factory',
    aiTier: 'esyai_advanced',
    priorityRanking: 2,
    features: [
      'Everything in Verified Seller',
      'Factory & Export License Verification',
      'Gold Badge on Profile',
      'Premium Trust Score (+20)',
      'AI Catalog & Pricing Optimizer',
      'AI Competitor Analysis',
      'AI Buyer Matching & Lead Suggestions',
      'AI Product Performance Analytics',
      'Featured Listings & Homepage Placement',
      'Unlimited Products',
      'Advanced Analytics & Sales Reports',
      'Priority Support',
    ],
    limits: {
      aiRequests: 2500,
      rfqs: 100,
      quotations: 150,
      products: -1,
      messages: 1000,
      serviceBookings: 50,
      marketInsights: 100,
      imageUploads: 500,
      documents: 1000,
    },
  },
  {
    key: 'seller_enterprise',
    role: 'seller',
    name: 'Enterprise Seller',
    description: 'Diamond verification, AI sales manager & global expansion tools',
    prices: { monthly: 14999, quarterly: 40499, yearly: 149990 },
    aiCredits: 10000,
    storageLimitMb: 51200,
    supportLevel: 'dedicated',
    trustScoreBoost: 30,
    verificationLevel: 'diamond',
    aiTier: 'esyai_enterprise',
    priorityRanking: 3,
    features: [
      'Everything in Gold Seller',
      'Diamond Badge (Highest Trust)',
      'Legal & Video Verification',
      'Premium Trust Score (+30)',
      'AI Sales Manager & Business Consultant',
      'AI Revenue Forecast & Global Expansion Insights',
      'AI Lead Qualification & Follow-up Automation',
      'AI Daily Sales Brief & Weekly Reports',
      'API Access',
      'Dedicated Success Manager',
      'Premium SLA Support',
      'Multi-User Workspace',
      'Custom Feature Development',
    ],
    limits: {
      aiRequests: 10000,
      rfqs: -1,
      quotations: -1,
      products: -1,
      messages: -1,
      serviceBookings: -1,
      marketInsights: -1,
      imageUploads: -1,
      documents: -1,
      teamMembers: -1,
    },
  },
];

export async function ensureSubscriptionPlans() {
  const count = await SubscriptionPlan.countDocuments();
  if (!count) {
    await SubscriptionPlan.insertMany(DEFAULT_PLANS);
  }
}

export async function getPlan(key, role) {
  await ensureSubscriptionPlans();
  const aliases = {
    free: `${role}_free`,
    basic: 'buyer_pro',
    standard: 'buyer_business',
    prime: 'buyer_enterprise',
    buyer_basic: 'buyer_pro',
    buyer_standard: 'buyer_business',
    buyer_prime: 'buyer_enterprise',
    verified_batch: 'seller_verified',
    verified_supplier: 'seller_gold',
  };
  return SubscriptionPlan.findOne({
    key: aliases[key] || key,
    role,
    status: 'active',
  }).lean();
}

export async function listPlans(role) {
  await ensureSubscriptionPlans();
  return SubscriptionPlan.find({ role, status: 'active' })
    .sort({ priorityRanking: 1 })
    .lean();
}