import SubscriptionPlan from '../models/SubscriptionPlan.js';

export const DEFAULT_PLANS = [
  // ==================== BUYER PLANS ====================
  {
    key: 'buyer_free',
    role: 'buyer',
    name: 'Free Buyer',
    description: 'For new buyers & small businesses starting their sourcing journey',
    prices: { monthly: 0, quarterly: 0, yearly: 0 },
    aiCredits: 50,
    storageLimitMb: 100,
    supportLevel: 'standard',
    trustScoreBoost: 0,
    verificationLevel: 'basic',
    aiTier: 'esyai_lite',
    priorityRanking: 0,
    features: [
      // Marketplace
      'Unlimited Product Browsing',
      'Unlimited Seller Browsing',
      'Basic Product Search',
      'Basic Supplier Search',
      'Save Products & Sellers',
      'Basic Wishlist',
      'Basic Messaging',
      'Basic RFQ Creation',
      'Standard Filters',
      // AI - EsyAI Lite
      'EsyAI Lite - Basic AI Chat',
      'Basic Product Suggestions',
      'Basic Supplier Suggestions',
      'Basic Image Search',
      'Basic Market Insights',
      'Basic Trade Calculator',
      // Trade
      'Basic Shipment Tracking',
      'Basic Order Tracking',
      'Standard Support',
    ],
    limits: {
      aiRequests: 50,
      rfqs: 3,
      quotations: 3,
      products: 0,
      messages: 20,
      serviceBookings: 2,
      marketInsights: 2,
      imageUploads: 5,
      documents: 10,
      savedProducts: 50,
      savedSellers: 20,
      wishlistItems: 30,
    },
  },
  {
    key: 'buyer_pro',
    role: 'buyer',
    name: 'Buyer Pro',
    description: 'Smart AI tools & priority access for serious buyers',
    prices: { monthly: 1499, quarterly: 3999, yearly: 14990 },
    aiCredits: 500,
    storageLimitMb: 2048,
    supportLevel: 'priority',
    trustScoreBoost: 5,
    verificationLevel: 'basic',
    aiTier: 'esyai_pro',
    priorityRanking: 1,
    features: [
      'Everything in Free Buyer',
      // AI - EsyAI Pro
      'EsyAI Pro - Advanced AI Engine',
      'Personalized Product Suggestions',
      'Personalized Supplier Suggestions',
      'AI Similar Products Finder',
      'AI Price Comparison',
      'AI MOQ Suggestions',
      'AI Product Comparison',
      'AI RFQ Generator',
      'AI RFQ Improvement',
      'AI Smart Replies',
      'AI Market Insights (Advanced)',
      'AI Product Discovery',
      'AI Category Suggestions',
      // Marketplace
      'Priority RFQs',
      'Unlimited Wishlist',
      'Advanced Search Filters',
      'Premium Seller Discovery',
      'AI Recommended Sellers',
      'AI Recommended Products',
      // Trade
      'Trade Assurance Access',
      'Escrow Access',
      'Better Shipment Tracking',
      'AI Shipping Suggestions',
      'Smart Notifications',
      'Priority Support',
    ],
    limits: {
      aiRequests: 500,
      rfqs: 20,
      quotations: 30,
      products: 0,
      messages: 200,
      serviceBookings: 10,
      marketInsights: 20,
      imageUploads: 100,
      documents: 200,
      savedProducts: 500,
      savedSellers: 200,
      wishlistItems: -1,
    },
  },
  {
    key: 'buyer_business',
    role: 'buyer',
    name: 'Buyer Business',
    description: 'Advanced trade intelligence & AI business assistant for growing importers',
    prices: { monthly: 3999, quarterly: 10799, yearly: 39990 },
    aiCredits: 2000,
    storageLimitMb: 10240,
    supportLevel: 'priority',
    trustScoreBoost: 10,
    verificationLevel: 'business',
    aiTier: 'esyai_advanced',
    priorityRanking: 2,
    features: [
      'Everything in Buyer Pro',
      // AI - EsyAI Advanced
      'EsyAI Advanced - Business AI Engine',
      'AI Business Advisor',
      'AI Negotiation Assistant',
      'AI Trade Consultant',
      'AI Import Guide',
      'AI Export Guide',
      'AI Customs Assistant',
      'AI Compliance Checker',
      'AI Documentation Assistant',
      'AI Product Research (Deep)',
      'AI Supplier Verification Suggestions',
      'AI Demand Forecast',
      'AI Trend Analysis',
      'AI Opportunity Finder',
      // Market Intelligence
      'Country Wise Trade Insights',
      'Import/Export Data Access',
      'Buyer Trends Analytics',
      'Supplier Trends Analytics',
      'Seasonal Demand Analysis',
      'Market Opportunity Reports',
      'HS Code Finder',
      'Tariff & Duty Calculator',
      // Business Features
      'Multi Team Access (Up to 5)',
      'Shared Wishlist',
      'Shared RFQs',
      'Advanced Analytics Dashboard',
      'Billing & Usage Analytics',
      'Dedicated Priority Support',
    ],
    limits: {
      aiRequests: 2000,
      rfqs: 100,
      quotations: 150,
      products: 0,
      messages: 1000,
      serviceBookings: 50,
      marketInsights: 100,
      imageUploads: 500,
      documents: 1000,
      savedProducts: -1,
      savedSellers: -1,
      wishlistItems: -1,
      teamMembers: 5,
    },
  },
  {
    key: 'buyer_enterprise',
    role: 'buyer',
    name: 'Buyer Enterprise',
    description: 'Full-scale enterprise procurement with personal AI trade consultant',
    prices: { monthly: 9999, quarterly: 26999, yearly: 99990 },
    aiCredits: 10000,
    storageLimitMb: 51200,
    supportLevel: 'dedicated',
    trustScoreBoost: 20,
    verificationLevel: 'enterprise',
    aiTier: 'esyai_enterprise',
    priorityRanking: 3,
    features: [
      'Everything in Buyer Business',
      // AI - EsyAI Enterprise
      'EsyAI Enterprise - Full AI Suite',
      'Personal AI Trade Consultant',
      'AI Executive Assistant',
      'AI Daily Business Brief',
      'AI Weekly Business Report',
      'AI Expansion Suggestions',
      'AI Risk Analysis',
      'AI Procurement Planning',
      'AI Supply Chain Optimization',
      'AI Profit Optimization',
      'AI Cost Reduction Recommendations',
      'AI Country Recommendation Engine',
      'AI Supplier Scoring System',
      'AI Lead Qualification',
      'AI Follow-up Suggestions',
      // Enterprise Features
      'API Access',
      'Dedicated Account Manager',
      'SLA Guaranteed Support',
      'Enterprise Dashboard',
      'Unlimited Team Workspace',
      'Advanced Custom Reports',
      'ERP Integration Ready',
      'Custom Integration Support',
      'White Label Reports',
      'Priority Feature Requests',
    ],
    limits: {
      aiRequests: 10000,
      rfqs: -1,
      quotations: -1,
      products: 0,
      messages: -1,
      serviceBookings: -1,
      marketInsights: -1,
      imageUploads: -1,
      documents: -1,
      savedProducts: -1,
      savedSellers: -1,
      wishlistItems: -1,
      teamMembers: -1,
    },
  },

  // ==================== SELLER PLANS ====================
  {
    key: 'seller_free',
    role: 'seller',
    name: 'Free Seller',
    description: 'Start selling on EsyGlob with basic store & tools',
    prices: { monthly: 0, quarterly: 0, yearly: 0 },
    aiCredits: 50,
    storageLimitMb: 100,
    supportLevel: 'standard',
    trustScoreBoost: 0,
    verificationLevel: 'basic',
    aiTier: 'esyai_lite',
    priorityRanking: 0,
    features: [
      // Marketplace
      'Basic Store Page',
      'Limited Products (Up to 5)',
      'Basic Analytics',
      'Basic RFQ Access',
      'Basic Messaging',
      // AI - EsyAI Lite
      'EsyAI Lite - Basic AI',
      'Basic Product Description Generator',
      'Basic Product Suggestions',
      // Verification
      'Basic KYC',
      'Mobile Verification',
      'Email Verification',
      'Standard Support',
    ],
    limits: {
      aiRequests: 50,
      rfqs: 3,
      quotations: 3,
      products: 5,
      messages: 20,
      serviceBookings: 2,
      marketInsights: 2,
      imageUploads: 5,
      documents: 10,
    },
  },
  {
    key: 'seller_verified',
    role: 'seller',
    name: 'Verified Seller',
    description: 'Get verified, build trust & unlock growth tools',
    prices: { monthly: 2499, quarterly: 6749, yearly: 24990 },
    aiCredits: 500,
    storageLimitMb: 2048,
    supportLevel: 'priority',
    trustScoreBoost: 10,
    verificationLevel: 'business',
    aiTier: 'esyai_pro',
    priorityRanking: 1,
    features: [
      'Everything in Free Seller',
      // Verification
      'GST Verification',
      'PAN Verification',
      'Aadhaar Verification',
      'Business Verification',
      'Bank Account Verification',
      'Verified Badge on Profile',
      'Higher Trust Score (+10)',
      // AI - EsyAI Pro
      'EsyAI Pro - Advanced AI Engine',
      'AI Product Description Generator (Advanced)',
      'AI SEO Title Generator',
      'AI Product Keywords Optimizer',
      'AI RFQ Suggestions',
      'AI Quotation Generator',
      'AI Product Improvement Suggestions',
      'AI Image Suggestions',
      // Marketplace
      'Better Search Ranking',
      'More Products (Up to 50)',
      'Priority RFQ Access',
      'Better Store Visibility',
      'Seller Analytics Dashboard',
      'Priority Support',
    ],
    limits: {
      aiRequests: 500,
      rfqs: 20,
      quotations: 30,
      products: 50,
      messages: 200,
      serviceBookings: 10,
      marketInsights: 20,
      imageUploads: 100,
      documents: 200,
    },
  },
  {
    key: 'seller_gold',
    role: 'seller',
    name: 'Gold Seller',
    description: 'Factory verified, priority ranking & AI-powered sales optimization',
    prices: { monthly: 5999, quarterly: 16199, yearly: 59990 },
    aiCredits: 2500,
    storageLimitMb: 10240,
    supportLevel: 'priority',
    trustScoreBoost: 20,
    verificationLevel: 'factory',
    aiTier: 'esyai_advanced',
    priorityRanking: 2,
    features: [
      'Everything in Verified Seller',
      // Premium Verification
      'Factory Verification',
      'Company Verification',
      'Export License Verification',
      'Gold Badge on Profile',
      'Premium Trust Score (+20)',
      // AI - EsyAI Advanced
      'EsyAI Advanced - Business AI Engine',
      'AI Catalog Optimizer',
      'AI Lead Suggestions',
      'AI Competitor Analysis',
      'AI Pricing Optimizer',
      'AI MOQ Optimizer',
      'AI Margin Calculator',
      'AI Inventory Suggestions',
      'AI Product Performance Analytics',
      'AI Sales Suggestions',
      'AI Buyer Matching',
      // Marketplace
      'Featured Listings',
      'Homepage Priority Placement',
      'Better Recommendation Ranking',
      'Advanced Seller Dashboard',
      'Advanced Analytics & Reports',
      'Unlimited Products',
      'Priority Support',
    ],
    limits: {
      aiRequests: 2500,
      rfqs: 100,
      quotations: 150,
      products: -1,
      messages: 1000,
      serviceBookings: 50,
      marketInsights: 100,
      imageUploads: 500,
      documents: 1000,
    },
  },
  {
    key: 'seller_enterprise',
    role: 'seller',
    name: 'Enterprise Seller',
    description: 'Diamond verification, AI sales manager & global expansion tools',
    prices: { monthly: 14999, quarterly: 40499, yearly: 149990 },
    aiCredits: 10000,
    storageLimitMb: 51200,
    supportLevel: 'dedicated',
    trustScoreBoost: 30,
    verificationLevel: 'diamond',
    aiTier: 'esyai_enterprise',
    priorityRanking: 3,
    features: [
      'Everything in Gold Seller',
      // Enterprise Verification
      'Diamond Badge - Highest Trust Level',
      'Premium Trust Score (+30)',
      'Video Verification',
      'Legal Document Verification',
      'Highest Search Ranking Priority',
      // AI - EsyAI Enterprise
      'EsyAI Enterprise - Full AI Suite',
      'AI Sales Manager',
      'AI Business Consultant',
      'AI Export Advisor',
      'AI Revenue Forecast',
      'AI Customer Behaviour Analysis',
      'AI Growth Strategy Recommendations',
      'AI Global Expansion Insights',
      'AI Smart Catalog Manager',
      'AI Lead Qualification',
      'AI Follow-up Automation',
      'AI Daily Sales Brief',
      'AI Weekly Performance Report',
      // Enterprise Features
      'Unlimited Products',
      'Unlimited Team Members',
      'Multi-User Workspace',
      'ERP Integration Ready',
      'API Access',
      'Dedicated Success Manager',
      'Advanced Custom Analytics',
      'Premium SLA Support',
      'Custom Feature Development',
    ],
    limits: {
      aiRequests: 10000,
      rfqs: -1,
      quotations: -1,
      products: -1,
      messages: -1,
      serviceBookings: -1,
      marketInsights: -1,
      imageUploads: -1,
      documents: -1,
      teamMembers: -1,
    },
  },
];

export async function ensureSubscriptionPlans() {
  const count = await SubscriptionPlan.countDocuments();
  if (!count) {
    await SubscriptionPlan.insertMany(DEFAULT_PLANS);
  }
  const experience = {
    buyer_free: { aiModel: 'EsyAI Lite', premiumBadge: 'Essential', businessGrowthScore: 15 },
    buyer_pro: { aiModel: 'DeepSeek AI', premiumBadge: 'Professional', popular: true, businessGrowthScore: 45 },
    buyer_business: { aiModel: 'ChatGPT AI', premiumBadge: 'Business Intelligence', recommended: true, businessGrowthScore: 75 },
    buyer_enterprise: { aiModel: 'Claude AI', premiumBadge: 'Enterprise', businessGrowthScore: 100 },
    seller_free: { aiModel: 'EsyAI Lite', premiumBadge: 'Starter', businessGrowthScore: 15 },
    seller_verified: { aiModel: 'DeepSeek AI', premiumBadge: 'Verified', popular: true, businessGrowthScore: 45 },
    seller_gold: { aiModel: 'ChatGPT AI', premiumBadge: 'Gold Growth', recommended: true, businessGrowthScore: 75 },
    seller_enterprise: { aiModel: 'Claude AI', premiumBadge: 'Enterprise', businessGrowthScore: 100 },
  };
  await Promise.all(Object.entries(experience).map(([key, metadata]) =>
    SubscriptionPlan.updateOne({ key }, { $set: metadata }),
  ));
}

export async function getPlan(key, role) {
  await ensureSubscriptionPlans();
  const aliases = {
    free: `${role}_free`,
    basic: 'buyer_pro',
    standard: 'buyer_business',
    prime: 'buyer_enterprise',
    buyer_basic: 'buyer_pro',
    buyer_standard: 'buyer_business',
    buyer_prime: 'buyer_enterprise',
    verified_batch: 'seller_verified',
    verified_supplier: 'seller_gold',
  };
  return SubscriptionPlan.findOne({
    key: aliases[key] || key,
    role,
    status: 'active',
  }).lean();
}

export async function listPlans(role) {
  await ensureSubscriptionPlans();
  return SubscriptionPlan.find({ role, status: 'active' })
    .sort({ priorityRanking: 1 })
    .lean();
}
