import SubscriptionPlan from '../models/SubscriptionPlan.js';

export const DEFAULT_PLANS = [
  ['buyer_free','buyer','Free',0,0,0,50,'ollama','Basic sourcing tools',0,'basic'], ['buyer_pro','buyer','Pro',799,2099,7990,500,'deepseek','More sourcing, RFQs and AI',5,'basic'], ['buyer_business','buyer','Business',1999,5399,19990,2000,'openai','Advanced trade intelligence',10,'business'], ['buyer_enterprise','buyer','Enterprise',4999,13499,49990,10000,'claude','Enterprise controls and support',20,'enterprise'],
  ['seller_free','seller','Free',0,0,0,50,'ollama','Start selling on EsyGlob',0,'basic'], ['seller_verified','seller','Verified',1499,4049,14990,500,'deepseek','Business verification and growth tools',10,'business'], ['seller_gold','seller','Gold',3499,9449,34990,2500,'openai','Factory verification and priority ranking',20,'factory'], ['seller_enterprise','seller','Enterprise',6999,18899,69990,10000,'claude','Diamond verification and enterprise scale',30,'diamond'],
].map(([key,role,name,monthly,quarterly,yearly,aiCredits,aiProvider,description,trustScoreBoost,verificationLevel], index) => ({ key, role, name, description, prices:{monthly,quarterly,yearly}, aiCredits, aiProvider, trustScoreBoost, verificationLevel, storageLimitMb:[100,2048,10240,51200][index%4], supportLevel:index%4>1?'priority':'standard', priorityRanking:index%4, features:index%4===0?['Core marketplace access','Basic support']:['Expanded usage limits','AI tools','Priority support','Billing and usage analytics'], limits:{ aiRequests:aiCredits, rfqs:[3,20,100,-1][index%4], quotations:[3,30,150,-1][index%4], products:role==='seller'?[5,50,250,-1][index%4]:0, messages:[20,200,1000,-1][index%4], serviceBookings:[2,10,50,-1][index%4], marketInsights:[2,20,100,-1][index%4], imageUploads:[5,100,500,-1][index%4], documents:[10,200,1000,-1][index%4] } }));

export async function ensureSubscriptionPlans() { const count=await SubscriptionPlan.countDocuments(); if(!count) await SubscriptionPlan.insertMany(DEFAULT_PLANS); }
export async function getPlan(key, role) { await ensureSubscriptionPlans(); const aliases={free:`${role}_free`,basic:'buyer_pro',standard:'buyer_business',prime:'buyer_enterprise',buyer_basic:'buyer_pro',buyer_standard:'buyer_business',buyer_prime:'buyer_enterprise',verified_batch:'seller_verified',verified_supplier:'seller_gold'}; return SubscriptionPlan.findOne({key:aliases[key]||key,role,status:'active'}).lean(); }
export async function listPlans(role) { await ensureSubscriptionPlans(); return SubscriptionPlan.find({role,status:'active'}).sort({priorityRanking:1}).lean(); }
