import { ArrowLeft, Banknote, Box, Calculator, ChartNoAxesCombined, ClipboardList, DollarSign, Package, Percent, ReceiptText, RefreshCw, ShieldCheck, Truck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import AppShell from '../components/AppShell'
import { CURRENCIES, useCurrency } from '../preferences/currency-context'

const tabs = [
  ['landed', 'Landed Cost', Package], ['simple', 'Calculator', Calculator], ['gst', 'GST', ReceiptText], ['duty', 'Import Duty', Banknote], ['freight', 'Freight', Truck], ['currency', 'Currency', DollarSign], ['profit', 'Profit', ChartNoAxesCombined], ['moq', 'MOQ Pricing', ClipboardList], ['packaging', 'Packaging', Box], ['summary', 'Trade Summary', Percent],
]
const countries = ['India', 'China', 'United States', 'United Arab Emirates', 'United Kingdom', 'Germany', 'Singapore', 'Vietnam', 'Bangladesh', 'Indonesia', 'Japan', 'Australia', 'Canada', 'Other']
const n = (value) => Number.isFinite(Number(String(value ?? '').replaceAll(',', ''))) ? Number(String(value ?? '').replaceAll(',', '')) : 0
const pct = (amount, rate) => amount * n(rate) / 100
const div = (amount, by) => n(by) > 0 ? amount / n(by) : 0

export default function TradeCalculatorPage() {
  const [params, setParams] = useSearchParams()
  const initial = tabs.some(([key]) => key === params.get('tab')) ? params.get('tab') : 'landed'
  const [active, setActive] = useState(initial)
  const [summary, setSummary] = useState(emptySummary)
  const current = tabs.find(([key]) => key === active)
  const Icon = current?.[2] || Calculator
  function choose(key) { setActive(key); setParams(key === 'landed' ? {} : { tab: key }, { replace: true }) }
  return <AppShell><div className="trade-calculator-page"><header className="trade-calc-head"><Link to="/services" aria-label="Back to services"><ArrowLeft /></Link><div><h1>Esy Trade Calculator</h1><p>Enterprise sourcing & trade utilities</p></div><i><Calculator /></i></header><nav className="trade-calc-tabs" aria-label="Calculator tools">{tabs.map(([key, label, TabIcon]) => <button className={active === key ? 'active' : ''} key={key} onClick={() => choose(key)}><TabIcon /><span>{label}</span></button>)}</nav><main><section className="trade-calc-hero"><i><Icon /></i><div><span>Trade intelligence</span><h2>{current?.[1]} Calculator</h2><p>{active === 'simple' ? 'Quick calculations for on-the-go trade math.' : 'Instant planning estimates for confident international trade decisions.'}</p></div></section><div className="trade-calc-module">{active === 'landed' && <Landed onSummary={setSummary} />}{active === 'simple' && <Simple />}{active === 'gst' && <Gst />}{active === 'duty' && <Duty />}{active === 'freight' && <Freight />}{active === 'currency' && <Currency />}{active === 'profit' && <Profit />}{active === 'moq' && <Moq />}{active === 'packaging' && <Packaging />}{active === 'summary' && <Summary initial={summary} />}</div>{active !== 'simple' && <div className="trade-calc-disclaimer"><ShieldCheck /><p>Planning estimates only. Confirm taxes, duty and freight with the appropriate authority or service provider before transacting.</p></div>}</main></div></AppShell>
}

function Landed({ onSummary }) {
  const { selectedCurrency, formatPrice } = useCurrency(); const [currency, setCurrency] = useState(selectedCurrency); const [v, setV] = useFields({ product: '', moq: '', quantity: '', freight: '', insurance: '', packaging: '', handling: '', loading: '', port: '', duty: '', gst: '18', platform: '', other: '', rate: '1', margin: '', incoterm: 'FOB' })
  const r = useMemo(() => { const quantity = n(v.quantity) || n(v.moq); const product = n(v.product) * quantity * (n(v.rate) || 1); const preDuty = product + n(v.freight) + n(v.insurance) + n(v.packaging) + n(v.handling) + n(v.loading) + n(v.port); const duty = pct(preDuty, v.duty); const gst = pct(preDuty + duty, v.gst); const platform = pct(product, v.platform); const total = preDuty + duty + gst + platform + n(v.other); const unit = div(total, quantity); const selling = n(v.margin) < 100 ? unit / (1 - n(v.margin) / 100) : unit; return { productCost: product, freight: n(v.freight), insurance: n(v.insurance), duty, gst, platformFee: platform, packaging: n(v.packaging), misc: n(v.handling) + n(v.loading) + n(v.port) + n(v.other), grandTotal: total, costPerUnit: unit, selling, gross: selling - unit } }, [v])
  useEffect(() => { onSummary(r) }, [onSummary, r])
  return <><Card title="Product & shipment" icon={Package}><Row><Field label="Unit product cost" value={v.product} set={setV('product')} suffix={currency} /><Field label="Quantity" value={v.quantity} set={setV('quantity')} suffix="units" /></Row><Row><Field label="MOQ" value={v.moq} set={setV('moq')} suffix="units" /><Select label="Currency" value={currency} set={setCurrency} options={CURRENCIES} /></Row><Row><Select label="Incoterm" value={v.incoterm} set={setV('incoterm')} options={['EXW', 'FOB', 'CIF', 'CFR', 'DAP', 'DDP']} /><Field label="Exchange rate" value={v.rate} set={setV('rate')} hint={`1 ${currency} in settlement currency`} /></Row></Card><Card title="Logistics & charges" icon={Truck}><Row><Field label="Freight" value={v.freight} set={setV('freight')} /><Field label="Insurance" value={v.insurance} set={setV('insurance')} /></Row><Row><Field label="Packaging" value={v.packaging} set={setV('packaging')} /><Field label="Handling" value={v.handling} set={setV('handling')} /></Row><Row><Field label="Loading" value={v.loading} set={setV('loading')} /><Field label="Port charges" value={v.port} set={setV('port')} /></Row><Field label="Other charges" value={v.other} set={setV('other')} /></Card><Card title="Taxes, fee & margin" icon={Percent}><Row><Field label="Duty" value={v.duty} set={setV('duty')} suffix="%" /><Field label="GST / Tax" value={v.gst} set={setV('gst')} suffix="%" /></Row><Row><Field label="Platform fee" value={v.platform} set={setV('platform')} suffix="%" /><Field label="Target gross margin" value={v.margin} set={setV('margin')} suffix="%" /></Row></Card><Result title="Total landed cost" value={formatPrice(r.grandTotal, currency)} rows={[['Product cost', formatPrice(r.productCost, currency)], ['Duty + GST', formatPrice(r.duty + r.gst, currency)], ['Cost per unit', formatPrice(r.costPerUnit, currency)], ['Estimated selling price', formatPrice(r.selling, currency), 'good'], ['Gross margin per unit', formatPrice(r.gross, currency), 'good']]} note="Customs values are estimates. Confirm HS code, origin rules and assessable value with a licensed customs professional." /></>
}

function Gst() { const { formatPrice } = useCurrency(); const [v, setV] = useFields({ amount: '', mode: 'exclusive', rate: '18', custom: '' }); const rate = v.rate === 'custom' ? n(v.custom) : n(v.rate); const r = useMemo(() => { const value = n(v.amount); if (v.mode === 'inclusive') { const net = value / (1 + rate / 100); return { net, gst: value - net, gross: value } } const gst = pct(value, rate); return { net: value, gst, gross: value + gst } }, [v, rate]); return <><Card title="GST calculation" icon={ReceiptText}><Select label="Tax treatment" value={v.mode} set={setV('mode')} options={[['exclusive', 'Exclusive GST'], ['inclusive', 'Inclusive GST']]} /><Row><Field label={v.mode === 'inclusive' ? 'Gross amount' : 'Net amount'} value={v.amount} set={setV('amount')} /><Select label="GST rate" value={v.rate} set={setV('rate')} options={[['5', '5% GST'], ['12', '12% GST'], ['18', '18% GST'], ['28', '28% GST'], ['custom', 'Custom rate']]} /></Row>{v.rate === 'custom' && <Field label="Custom GST rate" value={v.custom} set={setV('custom')} suffix="%" />}</Card><Result title="Gross amount" value={formatPrice(r.gross, 'INR')} rows={[['Net amount', formatPrice(r.net, 'INR')], [`GST (${rate}%)`, formatPrice(r.gst, 'INR')], ['Gross amount', formatPrice(r.gross, 'INR')]]} /></> }

function Duty() { const { formatPrice } = useCurrency(); const [v, setV] = useFields({ product: '', freight: '', insurance: '', bcd: '', sws: '10', igst: '18', other: '' }); const r = useMemo(() => { const assessable = n(v.product) + n(v.freight) + n(v.insurance); const bcd = pct(assessable, v.bcd); const sws = pct(bcd, v.sws); const igst = pct(assessable + bcd + sws, v.igst); const other = pct(assessable, v.other); const duty = bcd + sws + igst + other; return { assessable, bcd, sws, igst, other, duty, total: assessable + duty } }, [v]); return <><Card title="Customs value" icon={Package}><Field label="Product value" value={v.product} set={setV('product')} /><Row><Field label="Freight" value={v.freight} set={setV('freight')} /><Field label="Insurance" value={v.insurance} set={setV('insurance')} /></Row></Card><Card title="Duty rates" icon={Banknote}><Row><Field label="BCD" value={v.bcd} set={setV('bcd')} suffix="%" /><Field label="SWS on BCD" value={v.sws} set={setV('sws')} suffix="%" /></Row><Row><Field label="IGST" value={v.igst} set={setV('igst')} suffix="%" /><Field label="Other duties" value={v.other} set={setV('other')} suffix="%" /></Row></Card><Result title="Grand total" value={formatPrice(r.total, 'INR')} tone="amber" rows={[['Assessable value', formatPrice(r.assessable, 'INR')], ['BCD', formatPrice(r.bcd, 'INR')], ['SWS', formatPrice(r.sws, 'INR')], ['IGST', formatPrice(r.igst, 'INR')], ['Other duties', formatPrice(r.other, 'INR')], ['Total customs duty', formatPrice(r.duty, 'INR'), 'warn']]} note="Rates vary by HS code, country of origin, exemptions and customs notifications." /></> }

function Freight() { const { formatPrice } = useCurrency(); const [v, setV] = useFields({ mode: 'air', origin: 'India', destination: 'United States', weight: '', volume: '', cbm: '', rate: '' }); const r = useMemo(() => { const cbm = n(v.cbm) || n(v.volume); const air = v.mode === 'air' || v.mode === 'courier'; const chargeable = air ? Math.max(n(v.weight), cbm * 167) : Math.max(n(v.weight) / 1000, cbm); const defaults = { air: 5.5, sea: 90, road: 1.2, rail: .8, courier: 8 }; const days = { air: '3–7 days', sea: '20–45 days', road: '3–12 days', rail: '7–20 days', courier: '2–6 days' }; return { air, chargeable, cost: chargeable * (n(v.rate) || defaults[v.mode]), transit: days[v.mode] } }, [v]); return <><Card title="Shipment route" icon={Truck}><Select label="Freight mode" value={v.mode} set={setV('mode')} options={['air', 'sea', 'road', 'rail', 'courier']} /><Row><Select label="Origin" value={v.origin} set={setV('origin')} options={countries} /><Select label="Destination" value={v.destination} set={setV('destination')} options={countries} /></Row></Card><Card title="Cargo details" icon={Box}><Row><Field label="Weight" value={v.weight} set={setV('weight')} suffix="kg" /><Field label="Volume" value={v.volume} set={setV('volume')} suffix="m³" /></Row><Row><Field label="CBM" value={v.cbm} set={setV('cbm')} suffix="m³" /><Field label="Rate (optional)" value={v.rate} set={setV('rate')} suffix={r.air ? '/ kg' : '/ unit'} /></Row></Card><Result title="Estimated freight" value={formatPrice(r.cost, r.air ? 'USD' : 'INR')} rows={[['Route', `${v.origin} → ${v.destination}`], ['Chargeable measure', `${r.chargeable.toFixed(2)} ${r.air ? 'kg' : 'W/M'}`], ['Estimated transit time', r.transit]]} note="Indicative only. Carrier, route, fuel surcharge, cargo class and seasonal capacity affect final quotes." /></> }

function Currency() { const { rates, loading, error, refreshRates } = useCurrency(); const [v, setV] = useFields({ from: 'INR', to: 'USD', amount: '' }); const value = n(v.amount) / (rates[v.from] || 1) * (rates[v.to] || 1); const rate = 1 / (rates[v.from] || 1) * (rates[v.to] || 1); return <><Card title="Convert currency" icon={DollarSign}><Row><Select label="From" value={v.from} set={setV('from')} options={CURRENCIES} /><Select label="To" value={v.to} set={setV('to')} options={CURRENCIES} /></Row><Field label="Amount" value={v.amount} set={setV('amount')} suffix={v.from} /></Card><Result title="Converted amount" value={money(value, v.to)} rows={[['Current exchange rate', `1 ${v.from} = ${rate.toFixed(6)} ${v.to}`], ['Rates status', loading ? 'Updating…' : error ? 'Cached rates' : 'Updated within the last hour', error ? 'warn' : 'good']]} note={error || 'Rates are cached for one hour and refreshed by the existing global Currency Context.'} action={<button onClick={() => refreshRates(true)}><RefreshCw /> Refresh exchange rates</button>} /></> }

function Profit() { const { formatPrice } = useCurrency(); const [v, setV] = useFields({ buy: '', sell: '', quantity: '', expenses: '', platform: '', gst: '', shipping: '' }); const r = useMemo(() => { const revenue = n(v.sell) * n(v.quantity); const buying = n(v.buy) * n(v.quantity); const costs = buying + n(v.expenses) + n(v.shipping) + pct(revenue, v.platform) + pct(revenue, v.gst); const profit = revenue - costs; return { revenue, costs, profit, profitPct: div(profit, costs) * 100, margin: div(profit, revenue) * 100 } }, [v]); return <><Card title="Price & quantity" icon={ChartNoAxesCombined}><Row><Field label="Buying price" value={v.buy} set={setV('buy')} /><Field label="Selling price" value={v.sell} set={setV('sell')} /></Row><Field label="Quantity" value={v.quantity} set={setV('quantity')} /></Card><Card title="Costs" icon={Banknote}><Row><Field label="Expenses" value={v.expenses} set={setV('expenses')} /><Field label="Shipping" value={v.shipping} set={setV('shipping')} /></Row><Row><Field label="Platform fee" value={v.platform} set={setV('platform')} suffix="%" /><Field label="GST" value={v.gst} set={setV('gst')} suffix="%" /></Row></Card><Result title="Net earnings" value={formatPrice(r.profit, 'INR')} tone={r.profit >= 0 ? 'green' : 'amber'} rows={[['Revenue', formatPrice(r.revenue, 'INR')], ['Total costs', formatPrice(r.costs, 'INR')], ['Profit %', `${r.profitPct.toFixed(2)}%`, r.profit >= 0 ? 'good' : 'warn'], ['Margin', `${r.margin.toFixed(2)}%`, r.profit >= 0 ? 'good' : 'warn']]} /></> }

function Moq() { const { formatPrice } = useCurrency(); const [v, setV] = useFields({ quantity: '', moq1: '100', price1: '', moq2: '500', price2: '', moq3: '1000', price3: '' }); const tiers = [1, 2, 3].map((i) => ({ moq: n(v[`moq${i}`]), price: n(v[`price${i}`]) })).filter((x) => x.moq > 0).sort((a, b) => a.moq - b.moq); const selected = [...tiers].reverse().find((x) => n(v.quantity) >= x.moq) || tiers[0] || { moq: 0, price: 0 }; const order = n(v.quantity) * selected.price; const discount = Math.max(0, ((tiers[0]?.price || 0) - selected.price) * n(v.quantity)); return <><Card title="MOQ price tiers" icon={ClipboardList}>{[1, 2, 3].map((i) => <Row key={i}><Field label={`Tier ${i} MOQ`} value={v[`moq${i}`]} set={setV(`moq${i}`)} suffix="units" /><Field label={`Tier ${i} unit price`} value={v[`price${i}`]} set={setV(`price${i}`)} /></Row>)}</Card><Card title="Buyer quantity" icon={Package}><Field label="Order quantity" value={v.quantity} set={setV('quantity')} suffix="units" /></Card><Result title="Order value" value={formatPrice(order, 'INR')} tone="green" rows={[['Applied MOQ tier', selected.moq ? `${selected.moq}+ units` : '—'], ['Final unit cost', formatPrice(selected.price, 'INR')], ['Discount', formatPrice(discount, 'INR'), 'good'], ['Average cost', formatPrice(div(order, v.quantity), 'INR')]]} /></> }

function Packaging() { const [v, setV] = useFields({ length: '', width: '', height: '', weight: '', boxes: '1', unit: 'cm' }); const r = useMemo(() => { const divisor = v.unit === 'cm' ? 1_000_000 : v.unit === 'mm' ? 1_000_000_000 : 1; const boxVolume = n(v.length) * n(v.width) * n(v.height) / divisor; const cbm = boxVolume * n(v.boxes); const actual = n(v.weight) * n(v.boxes); return { boxVolume, cbm, actual, chargeable: Math.max(actual, cbm * 167) } }, [v]); return <><Card title="Package dimensions" icon={Box}><Select label="Dimension unit" value={v.unit} set={setV('unit')} options={[['cm', 'Centimetres (cm)'], ['mm', 'Millimetres (mm)'], ['m', 'Metres (m)']]} /><Row><Field label="Length" value={v.length} set={setV('length')} suffix={v.unit} /><Field label="Width" value={v.width} set={setV('width')} suffix={v.unit} /></Row><Row><Field label="Height" value={v.height} set={setV('height')} suffix={v.unit} /><Field label="Weight / box" value={v.weight} set={setV('weight')} suffix="kg" /></Row><Field label="Number of boxes" value={v.boxes} set={setV('boxes')} /></Card><Result title="Total packaging volume" value={`${r.cbm.toFixed(3)} CBM`} rows={[['Volume per box', `${r.boxVolume.toFixed(4)} m³`], ['Actual weight', `${r.actual.toFixed(2)} kg`], ['Air chargeable weight', `${r.chargeable.toFixed(2)} kg`]]} note="Air volumetric weight uses 167 kg per CBM. Carrier divisors can vary." /></> }

function Summary({ initial }) { const { formatPrice } = useCurrency(); const [v, setV] = useFields({ product: String(initial.productCost || ''), freight: String(initial.freight || ''), insurance: String(initial.insurance || ''), duty: String(initial.duty || ''), gst: String(initial.gst || ''), platform: String(initial.platformFee || ''), packaging: String(initial.packaging || ''), misc: String(initial.misc || ''), quantity: '' }); const total = Object.keys(v).filter((key) => key !== 'quantity').reduce((sum, key) => sum + n(v[key]), 0); return <><Card title="Consolidated trade costs" icon={ClipboardList}><Row><Field label="Product cost" value={v.product} set={setV('product')} /><Field label="Freight" value={v.freight} set={setV('freight')} /></Row><Row><Field label="Insurance" value={v.insurance} set={setV('insurance')} /><Field label="Duty" value={v.duty} set={setV('duty')} /></Row><Row><Field label="GST" value={v.gst} set={setV('gst')} /><Field label="Platform fee" value={v.platform} set={setV('platform')} /></Row><Row><Field label="Packaging" value={v.packaging} set={setV('packaging')} /><Field label="Misc charges" value={v.misc} set={setV('misc')} /></Row><Field label="Quantity" value={v.quantity} set={setV('quantity')} suffix="units" /></Card><Result title="Grand total" value={formatPrice(total, 'INR')} rows={[['Product cost', formatPrice(n(v.product), 'INR')], ['Logistics', formatPrice(n(v.freight) + n(v.insurance) + n(v.packaging), 'INR')], ['Taxes & duty', formatPrice(n(v.duty) + n(v.gst), 'INR')], ['Fees & misc', formatPrice(n(v.platform) + n(v.misc), 'INR')], ['Cost per unit', formatPrice(div(total, v.quantity), 'INR'), 'good']]} /></> }

function Simple() { const [display, setDisplay] = useState('0'); const [equation, setEquation] = useState(''); const [stored, setStored] = useState(null); const [operator, setOperator] = useState(''); const [reset, setReset] = useState(false); const calculate = (a, b, op) => op === '+' ? a + b : op === '−' ? a - b : op === '×' ? a * b : op === '÷' ? (b ? a / b : 0) : b; const format = (x) => Number.isInteger(x) ? String(x) : Number(x.toFixed(8)).toString(); function number(value) { setDisplay((current) => reset || current === '0' ? value : current + value); setReset(false) } function op(next) { const current = n(display); const value = stored === null ? current : calculate(stored, current, operator); setStored(value); setDisplay(format(value)); setEquation(`${format(value)} ${next}`); setOperator(next); setReset(true) } function equals() { if (stored === null || !operator) return; const current = n(display); setEquation(`${stored} ${operator} ${current} =`); setDisplay(format(calculate(stored, current, operator))); setStored(null); setOperator(''); setReset(true) } const keys = [['AC', 'fn'], ['±', 'fn'], ['%', 'fn'], ['÷', 'op'], ['7'], ['8'], ['9'], ['×', 'op'], ['4'], ['5'], ['6'], ['−', 'op'], ['1'], ['2'], ['3'], ['+', 'op'], ['⌫', 'fn'], ['0'], ['.'], ['=', 'equals']]; function press(key) { if (/^\d$/.test(key)) return number(key); if (['+', '−', '×', '÷'].includes(key)) return op(key); if (key === '=') return equals(); if (key === 'AC') { setDisplay('0'); setEquation(''); setStored(null); setOperator(''); setReset(false) } else if (key === '±') setDisplay(format(-n(display))); else if (key === '%') { setDisplay(format(n(display) / 100)); setReset(true) } else if (key === '.') { if (reset) { setDisplay('0.'); setReset(false) } else if (!display.includes('.')) setDisplay(`${display}.`) } else if (key === '⌫' && !reset) setDisplay((current) => current.length > 1 ? current.slice(0, -1) : '0') } return <div className="simple-calculator"><div className="simple-display"><small>{equation}</small><b>{display}</b></div><div className="simple-keypad">{keys.map(([key, type = 'num']) => <button className={type} key={key} onClick={() => press(key)}>{key}</button>)}</div></div> }

function useFields(initial) { const [values, setValues] = useState(initial); return [values, (key) => (value) => setValues((current) => ({ ...current, [key]: value }))] }
function Card({ title, icon: Icon, children }) { return <section className="calc-card"><header>{Icon && <i><Icon /></i>}<h3>{title}</h3></header>{children}</section> }
function Row({ children }) { return <div className="calc-field-row">{children}</div> }
function Field({ label, value, set, suffix, hint }) { return <label className="calc-field"><span>{label}</span><div><input type="number" inputMode="decimal" value={value} onChange={(event) => set(event.target.value)} placeholder="0" />{suffix && <b>{suffix}</b>}</div>{hint && <small>{hint}</small>}</label> }
function Select({ label, value, set, options }) { return <label className="calc-field"><span>{label}</span><div><select value={value} onChange={(event) => set(event.target.value)}>{options.map((option) => { const pair = Array.isArray(option) ? option : [option, String(option).replace(/^./, (x) => x.toUpperCase())]; return <option value={pair[0]} key={pair[0]}>{pair[1]}</option> })}</select></div></label> }
function Result({ title, value, rows, note, tone = 'indigo', action }) { return <section className={`calc-result ${tone}`}><header><i><ChartNoAxesCombined /></i><div><span>{title}</span><h3>{value}</h3></div></header>{rows.map(([label, rowValue, rowTone]) => <div className="calc-result-row" key={label}><span>{label}</span><b className={rowTone || ''}>{rowValue}</b></div>)}{note && <p>{note}</p>}{action && <footer>{action}</footer>}</section> }
function money(value, currency) { try { return new Intl.NumberFormat(currency === 'INR' ? 'en-IN' : 'en-US', { style: 'currency', currency, maximumFractionDigits: currency === 'INR' ? 0 : 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }
const emptySummary = { productCost: 0, freight: 0, insurance: 0, duty: 0, gst: 0, platformFee: 0, packaging: 0, misc: 0, grandTotal: 0, costPerUnit: 0 }
