import { Crosshair, Globe2, LocateFixed, MapPin, RefreshCw, ShieldCheck } from 'lucide-react'
import { useCallback, useState } from 'react'
import { fetchLocation, fetchProfile, toggleLocationTracking, updateLocation, updateProfile } from '../api/account'
import AppShell from '../components/AppShell'
import { PageHead } from '../components/PageHead'
import useAsyncData from '../hooks/useAsyncData'
import { TradeSkeleton } from './RfqsPage'

const countries = ['India','United States','United Kingdom','United Arab Emirates','China','Singapore','Canada','Australia','Germany','France','Japan','South Korea','Saudi Arabia','South Africa','Brazil']

export default function LocationPage() {
  const query = useAsyncData(useCallback(async () => { const [location, profile] = await Promise.all([fetchLocation().catch(() => ({})), fetchProfile()]); return { location: location.location, profile } }, []))
  const [form, setForm] = useState(null)
  const [busy, setBusy] = useState('')
  const [message, setMessage] = useState('')
  const data = query.data || {}; const current = data.location; const profile = data.profile || {}; const values = form || { country: profile.country || '', state: current?.address?.state || '', city: profile.city || current?.address?.city || '', shippingCountry: localStorage.getItem('esyglob.shippingCountry') || profile.country || '' }
  const change = (key, value) => setForm({ ...values, [key]: value })
  async function save(event) { event.preventDefault(); setBusy('save'); try { await updateProfile({ fullName: profile.fullName, companyName: profile.companyName || '', email: profile.email, phone: profile.phone || '', avatarUrl: profile.avatarUrl || '', country: values.country, city: values.city, address: profile.address || '', businessType: profile.businessType || '', companyDescription: profile.companyDescription || '' }); localStorage.setItem('esyglob.region', JSON.stringify({ country: values.country, state: values.state, city: values.city })); localStorage.setItem('esyglob.shippingCountry', values.shippingCountry); window.dispatchEvent(new Event('esyglob-region-change')); setMessage('Marketplace region and shipping country saved.'); await query.reload() } catch (error) { setMessage(error.message) } finally { setBusy('') } }
  function detect() { if (!navigator.geolocation) return setMessage('Location detection is not supported by this browser.'); setBusy('detect'); navigator.geolocation.getCurrentPosition(async (position) => { try { await updateLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, address: { country: values.country, state: values.state, city: values.city, formatted: [values.city, values.state, values.country].filter(Boolean).join(', ') } }); setMessage('Current location detected and saved securely.'); await query.reload() } catch (error) { setMessage(error.message) } finally { setBusy('') } }, (error) => { setBusy(''); setMessage(error.message) }, { enableHighAccuracy: true, timeout: 15000 }) }
  if (query.loading) return <AppShell><div className="container module-page"><TradeSkeleton /></div></AppShell>
  return <AppShell><div className="container module-page"><PageHead eyebrow="Marketplace preferences" title="Location and region" description="Choose your marketplace region, shipping country and preferred sourcing location." /><div className="location-layout"><form className="module-panel" onSubmit={save}><h2><Globe2 /> Region preferences</h2><div className="form-grid"><label>Marketplace country<select value={values.country} onChange={(e) => change('country', e.target.value)} required><option value="">Select country</option>{countries.map((item) => <option key={item}>{item}</option>)}</select></label><label>Shipping country<select value={values.shippingCountry} onChange={(e) => change('shippingCountry', e.target.value)} required><option value="">Select country</option>{countries.map((item) => <option key={item}>{item}</option>)}</select></label><label>State / province<input value={values.state} onChange={(e) => change('state', e.target.value)} /></label><label>City<input value={values.city} onChange={(e) => change('city', e.target.value)} required /></label></div><button className="button button--primary" disabled={Boolean(busy)}><MapPin /> Save preferred location</button></form><div className="module-panel location-detect"><h2><LocateFixed /> Device location</h2>{current?.current?.coordinates ? <div className="coordinate-card"><MapPin /><div><b>{current.address?.formatted || 'Detected coordinates'}</b><p>{current.current.coordinates[1]?.toFixed(5)}, {current.current.coordinates[0]?.toFixed(5)}</p><small>Accuracy {Math.round(current.accuracy || 0)} metres</small></div></div> : <p>No precise device location is stored.</p>}<div className="module-actions"><button className="button button--secondary" onClick={detect} disabled={Boolean(busy)}><Crosshair /> {busy === 'detect' ? 'Detecting…' : 'Detect now'}</button><button className="button button--secondary" onClick={async () => { setBusy('track'); await toggleLocationTracking(!current?.isActive); await query.reload(); setBusy('') }}><RefreshCw /> {current?.isActive ? 'Stop tracking' : 'Enable tracking'}</button></div><div className="privacy-note"><ShieldCheck /><p>Precise coordinates are stored only in your account and used for nearby suppliers, shipping estimates and delivery support.</p></div></div></div>{message && <p className={message.includes('saved') || message.includes('detected') ? 'action-success' : 'action-error'}>{message}</p>}</div></AppShell>
}
