import { ArrowRight, BarChart3, Boxes, GitCompareArrows, MessageSquare, PackageCheck, Target, WalletCards } from 'lucide-react'
import { useCallback, useMemo } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { fetchAccountSummary } from '../api/marketplace'
import { useAuth } from '../auth/auth-context'
import AppShell from '../components/AppShell'
import { Money, StatusBadge } from '../components/TradeUI'
import { PageHead } from '../components/PageHead'
import useAsyncData from '../hooks/useAsyncData'
import { TradeSkeleton } from './RfqsPage'

export default function MarketplaceDashboardPage(){const {user}=useAuth();const [params,setParams]=useSearchParams();const roles=user?.roles||['buyer'];const role=roles.includes('seller')&&params.get('role')==='seller'?'seller':'buyer';const query=useAsyncData(useCallback(()=>fetchAccountSummary(role),[role]));const metrics=useMemo(()=>dashboardMetrics(query.data,role),[query.data,role]);const links=role==='seller'?[['Products','/seller/products',Boxes],['RFQ opportunities','/rfqs?role=seller',Target],['Quotations','/quotations?role=seller',GitCompareArrows],['Orders','/orders?role=seller',PackageCheck],['Wallet','/wallet?role=seller',WalletCards],['Trade services','/services/requests',MessageSquare],['Market insights','/market-insights',BarChart3]]:[['My RFQs','/rfqs',Target],['Quotations','/quotations',GitCompareArrows],['Orders','/orders',PackageCheck],['Saved items','/saved',Boxes],['Wallet','/wallet',WalletCards],['Trade services','/services/requests',MessageSquare],['AI sourcing','/ai-chat',MessageSquare]];return <AppShell><div className="container module-page"><PageHead eyebrow={`${role} workspace`} title={`${role==='seller'?'Seller':'Buyer'} dashboard`} description="A live overview of marketplace activity and the next actions in your trade workflow." />{roles.includes('seller')&&<div className="role-switch dashboard-role"><button className={role==='buyer'?'active':''} onClick={()=>setParams({role:'buyer'})}>Buyer</button><button className={role==='seller'?'active':''} onClick={()=>setParams({role:'seller'})}>Seller</button></div>}{query.loading?<TradeSkeleton/>:<><div className="dashboard-metrics">{metrics.map(item=><article key={item.label}><i><item.icon/></i><div><small>{item.label}</small><b>{item.money?<Money value={item.value}/>:Number(item.value||0).toLocaleString()}</b><span>{item.note}</span></div></article>)}</div><div className="dashboard-grid"><section className="module-panel"><h2>Marketplace workspace</h2><div className="dashboard-links">{links.map(([label,to,Icon])=><Link to={to} key={label}><Icon/><span><b>{label}</b><small>Open and manage</small></span><ArrowRight/></Link>)}</div></section><section className="module-panel"><h2>Account readiness</h2><div className="readiness-list"><p><StatusBadge status={user?.emailVerified?'verified':'pending'}/> Email verification</p><p><StatusBadge status={user?.phoneVerified?'verified':'pending'}/> Phone verification</p><p><StatusBadge status={role==='seller'?(query.data?.[4]?.isVerified?'verified':'pending'):'active'}/> {role==='seller'?'Seller verification':'Buyer account'}</p></div><Link className="button button--secondary button--full" to="/profile">Complete profile</Link></section></div></>}</div></AppShell>}
function dashboardMetrics(data,role){const [,orders,,wallet,last]=data||[];return role==='seller'?[{label:'Products',value:last?.totalProducts||last?.seller?.totalProducts,icon:Boxes,note:'Catalog listings'},{label:'Orders',value:orders?.pagination?.total||orders?.orders?.length,icon:PackageCheck,note:'Seller orders'},{label:'Balance',value:wallet?.summary?.balance,icon:WalletCards,money:true,note:'Wallet balance'},{label:'Withdrawable',value:wallet?.summary?.withdrawableAmount,icon:BarChart3,money:true,note:'Available settlement'}]:[{label:'Orders',value:orders?.pagination?.total||orders?.orders?.length,icon:PackageCheck,note:'Trade orders'},{label:'Saved',value:last?.items?.length||last?.savedItems?.length,icon:Boxes,note:'Shortlisted items'},{label:'Balance',value:wallet?.summary?.balance,icon:WalletCards,money:true,note:'Wallet balance'},{label:'Refunds',value:wallet?.summary?.refundedAmount,icon:BarChart3,money:true,note:'Returned funds'}]}
