import { Building2, Mail, MapPin, Phone, Save, UserRound } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { fetchProfile, updateProfile } from '../api/account'
import AppShell from '../components/AppShell'
import { AttachmentUploader } from '../components/TradeUI'
import { PageHead } from '../components/PageHead'
import useAsyncData from '../hooks/useAsyncData'
import { TradeSkeleton } from './RfqsPage'

const empty={fullName:'',companyName:'',email:'',phone:'',avatarUrl:'',country:'',city:'',address:'',businessType:'',companyDescription:''}
// eslint-disable-next-line react-hooks/use-memo, react-hooks/set-state-in-effect
export default function ProfilePage(){const query=useAsyncData(useCallback(fetchProfile,[]));const [form,setForm]=useState(empty);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');useEffect(()=>{if(query.data)setForm({...empty,...query.data})},[query.data]);async function save(e){e.preventDefault();setBusy(true);setMessage('');try{await updateProfile(form);setMessage('Profile updated successfully.');query.reload()}catch(error){setMessage(error.message)}finally{setBusy(false)}}if(query.loading)return <AppShell><div className="container module-page"><TradeSkeleton/></div></AppShell>;return <AppShell><div className="container module-page"><PageHead eyebrow="Account identity" title="Profile" description="Keep your buyer and seller identity accurate across marketplace conversations and trade documents." /><form className="profile-layout" onSubmit={save}><aside className="module-panel profile-avatar"><div>{form.avatarUrl?<img src={form.avatarUrl} alt=""/>:<UserRound/>}</div><h2>{form.fullName||'EsyGlob member'}</h2><p>{form.companyName||form.email}</p><AttachmentUploader folder="profiles" accept="image/*" value={form.avatarUrl?[{url:form.avatarUrl,filename:'Profile image'}]:[]} onChange={(files)=>setForm({...form,avatarUrl:files.at(-1)?.url||''})}/></aside><div><section className="module-panel"><h2><UserRound/> Personal details</h2><div className="form-grid"><Field icon={UserRound} label="Full name" name="fullName" form={form} setForm={setForm}/><Field icon={Mail} label="Email" name="email" type="email" form={form} setForm={setForm}/><Field icon={Phone} label="Phone" name="phone" form={form} setForm={setForm}/></div></section><section className="module-panel"><h2><Building2/> Business profile</h2><div className="form-grid"><Field icon={Building2} label="Company" name="companyName" form={form} setForm={setForm}/><Field label="Business type" name="businessType" form={form} setForm={setForm}/><Field icon={MapPin} label="Country" name="country" form={form} setForm={setForm}/><Field label="City" name="city" form={form} setForm={setForm}/></div><label className="field-wide">Address<input value={form.address} onChange={(e)=>setForm({...form,address:e.target.value})}/></label><label className="field-wide">Company description<textarea value={form.companyDescription} onChange={(e)=>setForm({...form,companyDescription:e.target.value})} maxLength="2000"/></label></section>{message&&<p className={message.includes('successfully')?'action-success':'action-error'}>{message}</p>}<button className="button button--primary" disabled={busy}><Save/> {busy?'Saving…':'Save profile'}</button></div></form></div></AppShell>}
function Field({icon:Icon,label,name,type='text',form,setForm}){return <label>{label}<span className="input-with-icon">{Icon&&<Icon/>}<input type={type} value={form[name]} onChange={(e)=>setForm({...form,[name]:e.target.value})} required={['fullName','email'].includes(name)}/></span></label>}
