/* eslint-disable react-hooks/set-state-in-effect */
import { Building2, Check, ChevronLeft, ChevronRight, CircleAlert, Clock3, FileCheck2, Landmark, MapPin, ShieldCheck, Upload, UserCheck, Warehouse } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import AppShell from '../components/AppShell'
import { archiveVerificationDocument, fetchVerificationWorkspace, saveVerificationDraft, uploadVerificationDocument } from '../api/verification'

const steps = [
  { key:'company', label:'Company', icon:Building2, fields:[['companyName','Legal company name'],['companyType','Business type'],['yearEstablished','Year established'],['businessEmail','Business email'],['businessPhone','Business phone'],['companyDescription','Company overview']] },
  { key:'registration', label:'Registration', icon:FileCheck2, fields:[['gstNumber','GST number'],['panNumber','PAN number'],['businessRegistrationNumber','Registration number'],['importExportCode','Import Export Code']], docs:[['business_registration','Business registration'],['gst_certificate','GST certificate'],['pan_card','PAN card'],['import_export_code','IEC certificate']] },
  { key:'identity', label:'Identity', icon:UserCheck, fields:[['authorizedPerson','Authorized representative'],['designation','Designation']], docs:[['government_id_front','Government ID front'],['government_id_back','Government ID back'],['director_id','Director identity proof']] },
  { key:'address', label:'Address', icon:MapPin, fields:[['street','Street address'],['city','City'],['state','State'],['country','Country'],['pincode','Postal code']], docs:[['address_proof','Registered address proof'],['utility_bill','Recent utility bill'],['lease_agreement','Lease agreement']] },
  { key:'factory', label:'Factory', icon:Warehouse, fields:[], docs:[['factory_license','Factory licence'],['factory_image','Factory photographs'],['production_line_image','Production line'],['machinery_image','Machinery']] },
  { key:'certifications', label:'Certifications', icon:ShieldCheck, fields:[['certificationNames','Certification names']], docs:[['quality_certificate','Quality certificate'],['certification','Other certification']] },
  { key:'bank', label:'Bank', icon:Landmark, fields:[['bankName','Bank name'],['accountHolderName','Account holder'],['accountNumber','Account number'],['ifscCode','IFSC / routing code']], docs:[['cancelled_cheque','Cancelled cheque'],['bank_certificate','Bank certificate']] },
  { key:'review', label:'Review', icon:Check, fields:[] },
]
const statusLabel = value => String(value || 'draft').replaceAll('_',' ')
const valueAt = (data, step, key) => step === 'company' ? data.seller?.[key] ?? data.verification?.stepData?.business?.[key] ?? '' : step === 'address' ? data.seller?.address?.[key] ?? data.verification?.stepData?.address?.[key] ?? '' : data.verification?.stepData?.[step]?.[key] ?? data.verification?.stepData?.business?.[key] ?? data.seller?.bankDetails?.[key] ?? data.seller?.[key] ?? ''

export default function SellerVerificationPage(){
  const [data,setData]=useState(null),[active,setActive]=useState(0),[form,setForm]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('')
  const load=useCallback(()=>fetchVerificationWorkspace().then(result=>{setData(result);setActive(result.verificationCenter?.currentStep||0)}).catch(e=>setError(e.message)),[])
  useEffect(()=>{load()},[load])
  useEffect(()=>{if(!data)return;const next={};steps.forEach(s=>s.fields.forEach(([key])=>{next[`${s.key}.${key}`]=valueAt(data,s.key,key)}));setForm(next)},[data])
  const docs=useMemo(()=>(data?.verification?.documents||[]).filter(d=>d.status!=='archived'),[data])
  async function persist(submitForReview=false){setBusy(true);setError('');try{const stepData={...(data?.verification?.stepData||{})};steps.forEach(s=>{stepData[s.key]={...(stepData[s.key]||{})};s.fields.forEach(([key])=>{stepData[s.key][key]=form[`${s.key}.${key}`]})});const company=stepData.company||{}, address=stepData.address||{};await saveVerificationDraft({companyName:company.companyName||undefined,companyType:company.companyType||undefined,businessEmail:company.businessEmail||undefined,businessPhone:company.businessPhone||undefined,gstNumber:stepData.registration?.gstNumber||undefined,panNumber:stepData.registration?.panNumber||undefined,address,verificationCenter:{currentStep:active,stepData,submitForReview}});setSaved(submitForReview?'Submitted for review':'Draft saved');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function upload(type,file){if(!file)return;setBusy(true);try{await uploadVerificationDocument(type,file);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const current=steps[active], status=data?.verification?.status||'draft', manufacturer=(form['company.companyType']||data?.seller?.companyType)==='manufacturer'
  if(!data&&!error)return <AppShell><div className="container verification-loading">Loading verification workspace…</div></AppShell>
  return <AppShell><main className="container verification-page"><header className="verification-hero"><div><span className="eyebrow">Seller trust centre</span><h1>Business verification</h1><p>Build buyer confidence with verified company, identity, factory and banking credentials.</p></div><div className={`verification-status status-${status}`}><ShieldCheck/><span><small>Application status</small><b>{statusLabel(status)}</b></span></div></header>
  {error&&<div className="verification-alert"><CircleAlert/>{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
  <section className="verification-summary"><article><b>{data?.verificationCenter?.completionPercentage||0}%</b><span>Application complete</span><em><i style={{width:`${data?.verificationCenter?.completionPercentage||0}%`}}/></em></article><article><b>{data?.verificationCenter?.overallTrustScore||0}/100</b><span>Trust readiness</span></article><article><b>{docs.filter(d=>['verified','approved'].includes(d.status)).length}</b><span>Documents verified</span></article><article><b>{statusLabel(data?.verificationCenter?.currentLevel||'Unverified')}</b><span>Current level</span></article></section>
  <div className="verification-layout"><aside className="verification-steps">{steps.map((s,index)=>{const Icon=s.icon,done=data?.verificationCenter?.completedSteps?.includes(index);return <button key={s.key} className={active===index?'active':''} onClick={()=>setActive(index)}><i>{done?<Check/>:<Icon/>}</i><span><b>{s.label}</b><small>{done?'Complete':index===active?'In progress':'Not completed'}</small></span></button>})}<a href="/seller/factory"><Warehouse/>Manage factory profile<ChevronRight/></a></aside>
  <section className="verification-workspace"><header><current.icon/><div><span>Step {active+1} of {steps.length}</span><h2>{current.label} verification</h2></div>{saved&&<small>{saved}</small>}</header>
  {current.key==='factory'&&<div className="factory-callout"><Warehouse/><div><b>{manufacturer?'Complete your manufacturing profile':'Factory details are optional'}</b><p>The factory profile is shared with your public supplier page and can be maintained independently.</p></div><a className="button button--secondary" href="/seller/factory">Open factory manager</a></div>}
  {current.key==='review'?<ReviewPanel data={data} docs={docs}/>:<><div className="verification-fields">{current.fields.map(([key,label])=><label key={key}><span>{label}</span>{key==='companyType'?<select value={form[`${current.key}.${key}`]||''} onChange={e=>setForm({...form,[`${current.key}.${key}`]:e.target.value})}><option value="">Select type</option>{['manufacturer','wholesaler','distributor','trader','exporter','other'].map(x=><option key={x}>{x}</option>)}</select>:key==='companyDescription'?<textarea value={form[`${current.key}.${key}`]||''} onChange={e=>setForm({...form,[`${current.key}.${key}`]:e.target.value})}/>:<input value={form[`${current.key}.${key}`]||''} onChange={e=>setForm({...form,[`${current.key}.${key}`]:e.target.value})}/>}</label>)}</div><DocumentGrid definitions={current.docs||[]} docs={docs} busy={busy} upload={upload} remove={async id=>{await archiveVerificationDocument(id);load()}}/></>}
  <footer><button className="button button--ghost" disabled={active===0} onClick={()=>setActive(x=>x-1)}><ChevronLeft/>Previous</button><button className="button button--ghost" disabled={busy} onClick={()=>persist(false)}>{busy?'Saving…':'Save draft'}</button>{active<7?<button className="button button--primary" onClick={()=>{persist(false);setActive(x=>x+1)}}>Save & continue<ChevronRight/></button>:<button className="button button--primary" disabled={busy||['submitted','under_review','approved'].includes(status)} onClick={()=>persist(true)}>Submit for review</button>}</footer></section>
  <aside className="verification-timeline"><h2>Application timeline</h2>{(data?.timeline||[]).length?(data.timeline||[]).slice().reverse().map(item=><article key={item._id}><i/><div><b>{statusLabel(item.toStatus||item.action)}</b><p>{item.notes||statusLabel(item.action)}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div></article>):<div className="empty-timeline"><Clock3/><p>Your application history will appear here.</p></div>}</aside></div></main></AppShell>}

function DocumentGrid({definitions,docs,busy,upload,remove}){if(!definitions.length)return null;return <div className="verification-docs"><h3>Supporting documents</h3>{definitions.map(([type,label])=>{const item=[...docs].reverse().find(d=>d.type===type);return <article key={type}><FileCheck2/><span><b>{label}</b><small>{item?`${statusLabel(item.status)} · v${item.version||1}`:'PDF, JPG or PNG · max 5 MB'}</small></span>{item?<><a href={item.downloadUrl||item.url} target="_blank" rel="noreferrer">View</a><button onClick={()=>remove(item._id)}>Remove</button></>:<label className="upload-button"><Upload/>Upload<input type="file" disabled={busy} accept=".pdf,.png,.jpg,.jpeg" onChange={e=>upload(type,e.target.files?.[0])}/></label>}</article>})}</div>}
function ReviewPanel({data,docs}){return <div className="verification-review"><ShieldCheck/><h3>Review your application</h3><p>Confirm the details are current and the uploaded files are readable. Once submitted, reviewers may request more information or schedule a factory inspection.</p><div><span><b>{data?.seller?.companyName||'Company details'}</b><small>Company and registration profile</small></span><Check/><span><b>{docs.length} documents</b><small>{docs.filter(d=>['rejected','needs_update'].includes(d.status)).length} require attention</small></span><Check/></div></div>}
