/* eslint-disable react-hooks/exhaustive-deps */
import { Boxes, Copy, Edit3, Eye, Grid2X2, List, PackagePlus, Search, Trash2 } from 'lucide-react'
import { useCallback, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { createSellerProduct, deleteSellerProduct, fetchSellerProducts } from '../api/account'
import AppShell from '../components/AppShell'
import { SafeImage } from '../components/MarketplaceCards'
import { Money, StatusBadge } from '../components/TradeUI'
import { PageHead } from '../components/PageHead'
import useAsyncData from '../hooks/useAsyncData'
import { resolveId } from '../utils/trade'
import { TradeSkeleton } from './RfqsPage'

const statuses = ['all','draft','published','active','paused','pending_review','rejected']
export default function SellerProductsPage() {
  const navigate = useNavigate(); const [params,setParams]=useSearchParams(); const status=params.get('status')||'all'; const page=Number(params.get('page')||1); const q=params.get('q')||''; const [search,setSearch]=useState(q); const [view,setView]=useState('grid'); const [sort,setSort]=useState('latest')
  const query=useAsyncData(useCallback(()=>fetchSellerProducts({ q:q||undefined,status:status==='all'?undefined:status,page,sort }),[page,q,sort,status])); const products=query.data?.products||[]; const sorted=useMemo(()=>[...products].sort((a,b)=>sort==='price_desc'?Number(b.price)-Number(a.price):sort==='price_asc'?Number(a.price)-Number(b.price):new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt)),[products,sort]); const set=(key,value)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next)}
  async function remove(item){if(!window.confirm(`Delete ${item.name}? This cannot be undone.`))return;await deleteSellerProduct(resolveId(item));query.reload()}
  async function duplicate(item){const copy={...item,name:`${item.name} copy`,status:'draft',images:item.images||[],categoryId:resolveId(item.categoryId),sellerId:undefined,_id:undefined,id:undefined,slug:undefined,createdAt:undefined,updatedAt:undefined};await createSellerProduct(copy);query.reload()}
  return <AppShell><div className="container module-page"><PageHead eyebrow="Seller catalog" title="Products" description="Publish and manage pricing, MOQ, variants, inventory and product visibility." /><div className="module-actions"><Link className="button button--primary" to="/seller/products/new"><PackagePlus /> Add product</Link><div className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 /></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List /></button></div></div><div className="module-toolbar"><form onSubmit={(e)=>{e.preventDefault();set('q',search.trim())}}><Search /><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search your catalog" /><button>Search</button></form><select value={status} onChange={(e)=>set('status',e.target.value)}>{statuses.map(item=><option key={item}>{item}</option>)}</select><select value={sort} onChange={(e)=>setSort(e.target.value)}><option value="latest">Recently updated</option><option value="price_asc">Price low to high</option><option value="price_desc">Price high to low</option></select></div>{query.loading?<TradeSkeleton/>:query.error?<p className="inline-error">{query.error.message}</p>:sorted.length?<div className={`seller-product-grid ${view==='list'?'is-list':''}`}>{sorted.map(item=><article key={resolveId(item)}><SafeImage src={item.images?.[0]||item.image} alt={item.name}/><div><div className="trade-heading-line"><StatusBadge status={item.status||'draft'}/><small>{item.stockQuantity??0} in stock</small></div><h2>{item.name}</h2><b><Money value={item.price} currency={item.currency}/></b><p>MOQ {item.minimumOrderQuantity||1} {item.unit||'piece'} · {item.variants?.length||0} variants</p><div className="product-stats"><span><b>{item.views||item.viewCount||0}</b> views</span><span><b>{item.totalOrders||0}</b> orders</span><span><b>{Number(item.averageRating||0).toFixed(1)}</b> rating</span></div><div className="seller-product-actions"><button onClick={()=>navigate(`/seller/products/${resolveId(item)}/edit`)}><Edit3/> Edit</button><Link to={`/products/${resolveId(item)}`}><Eye/> View</Link><button onClick={()=>duplicate(item)}><Copy/> Duplicate</button><button className="danger-text" onClick={()=>remove(item)}><Trash2/></button></div></div></article>)}</div>:<div className="empty-results"><Boxes/><h2>No products found</h2><p>Add your first product or change the active filters.</p><Link className="button button--primary" to="/seller/products/new">Add product</Link></div>}<div className="pagination-row"><button disabled={page<=1} onClick={()=>set('page',String(page-1))}>Previous</button><span>Page {page}</span><button disabled={!query.data?.pagination?.hasNextPage&&products.length<30} onClick={()=>set('page',String(page+1))}>Next</button></div></div></AppShell>
}
