import { ArrowLeft, Calculator, CheckCircle2, FileUp, Send, ShieldCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { createServiceRequest, fetchServiceQuote, getService } from '../api/services'
import { useAuth } from '../auth/auth-context'
import AppShell from '../components/AppShell'
import { AttachmentUploader, Money } from '../components/TradeUI'

export default function ServiceBookingPage() {
  const { serviceKey } = useParams(); const service = getService(serviceKey); const { user } = useAuth(); const navigate = useNavigate()
  const roles = user?.roles || [user?.primaryRole || 'buyer']; const [role, setRole] = useState(service?.role === 'seller' ? 'seller' : service?.role === 'buyer' ? 'buyer' : roles.includes('seller') && user?.primaryRole === 'seller' ? 'seller' : 'buyer')
  const [values, setValues] = useState({ priority: 'normal', contactName: user?.name || '', contactEmail: user?.email || '', contactPhone: user?.phone || '' }); const [documents, setDocuments] = useState([]); const [quote, setQuote] = useState(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const sections = useMemo(() => service ? [...new Set(service.fields.map((item) => item.step || 'Booking details'))] : [], [service])
  if (!service) return <AppShell><div className="container module-page"><p className="inline-error">Service not found.</p></div></AppShell>
  if (service.role === 'seller' && !roles.includes('seller')) return <AppShell><div className="container module-page"><div className="empty-results"><ShieldCheck /><h2>Seller account required</h2><p>Complete seller onboarding before requesting business verification.</p><Link className="button button--primary" to="/profile">Review profile</Link></div></div></AppShell>
  function change(key, value) { setValues((current) => ({ ...current, [key]: value })); setQuote(null) }
  async function calculate() { setBusy('quote'); setError(''); try { setQuote(await fetchServiceQuote(service.key, values)) } catch (next) { setError(next.message) } finally { setBusy('') } }
  async function submit(event) { event.preventDefault(); setBusy('submit'); setError(''); try { const request = await createServiceRequest(service, role, values, documents); navigate(`/services/requests/${request._id || request.id}`, { state: { created: true } }) } catch (next) { setError(next.message); setBusy('') } }
  return <AppShell><div className="container service-booking-page"><Link className="back-link" to={`/services/${service.key}`}><ArrowLeft /> {service.title}</Link><header><span className="eyebrow">Secure service booking</span><h1>Book {service.title}</h1><p>Complete the requirements below. You can review pricing before submitting.</p></header>{roles.includes('seller') && service.role === 'both' && <div className="role-switch"><button className={role === 'buyer' ? 'active' : ''} onClick={() => setRole('buyer')}>Book as buyer</button><button className={role === 'seller' ? 'active' : ''} onClick={() => setRole('seller')}>Book as seller</button></div>}<form onSubmit={submit} className="service-booking-layout"><div>{sections.map((section) => <section className="module-panel service-form-section" key={section}><h2>{section}</h2><div className="form-grid">{service.fields.filter((item) => (item.step || 'Booking details') === section).map((item) => <ServiceField key={item.key} field={item} value={values[item.key] || ''} onChange={(value) => change(item.key, value)} />)}</div></section>)}<section className="module-panel service-form-section"><h2><FileUp /> Supporting documents</h2><p>Upload invoices, product specifications, registrations or evidence relevant to this booking.</p><AttachmentUploader folder="service-requests" value={documents} onChange={setDocuments} accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" /></section></div><aside className="module-panel service-quote-card"><ShieldCheck /><h2>Booking summary</h2><p>{service.title}</p><label>Priority<select value={values.priority} onChange={(event) => change('priority', event.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label>{quote ? <div className="quote-breakdown"><span>Base cost <b><Money value={quote.baseCost} currency={quote.currency} /></b></span><span>Additional charges <b><Money value={quote.additionalCharges} currency={quote.currency} /></b></span><span>Platform fee <b><Money value={quote.platformFee} currency={quote.currency} /></b></span><span>GST ({quote.gstRate}%) <b><Money value={quote.gstAmount} currency={quote.currency} /></b></span><strong>Total <b><Money value={quote.totalPayable} currency={quote.currency} /></b></strong></div> : <button type="button" className="button button--secondary button--full" onClick={calculate} disabled={Boolean(busy)}><Calculator /> {busy === 'quote' ? 'Calculating…' : 'Calculate quote'}</button>}{error && <p className="action-error">{error}</p>}<button className="button button--primary button--full" disabled={Boolean(busy)}><Send /> {busy === 'submit' ? 'Submitting…' : 'Submit booking'}</button><small><CheckCircle2 /> Payment is requested securely after the booking is created.</small></aside></form></div></AppShell>
}

function ServiceField({ field, value, onChange }) { const props = { value, required: field.required, onChange: (event) => onChange(event.target.value) }; return <label className={field.type === 'textarea' ? 'field-wide' : ''}>{field.label}{field.type === 'select' ? <select {...props}><option value="">Select</option>{field.options.map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select> : field.type === 'textarea' ? <textarea {...props} rows="4" /> : <input {...props} type={field.type || 'text'} min={field.type === 'number' ? 0 : undefined} />}</label> }
