import { ArrowRight, CalendarDays, Search, SlidersHorizontal } from 'lucide-react'
import { useCallback, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { fetchServiceRequests } from '../api/services'
import { useAuth } from '../auth/auth-context'
import AppShell from '../components/AppShell'
import { PageHead } from '../components/PageHead'
import { Money, StatusBadge } from '../components/TradeUI'
import useAsyncData from '../hooks/useAsyncData'
import { resolveId } from '../utils/trade'
import { TradeSkeleton } from './RfqsPage'

export default function ServiceRequestsPage() { const { user } = useAuth(); const roles = user?.roles || [user?.primaryRole || 'buyer']; const [role, setRole] = useState(roles.includes('seller') && user?.primaryRole === 'seller' ? 'seller' : 'buyer'); const [status, setStatus] = useState('all'); const [search, setSearch] = useState(''); const query = useAsyncData(useCallback(() => fetchServiceRequests({ role, status: status === 'all' ? undefined : status }), [role, status])); const items = useMemo(() => (query.data || []).filter((item) => `${item.serviceTitle} ${item.requestNumber}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]); return <AppShell><div className="container module-page"><PageHead eyebrow="Trade operations" title="Service booking history" description="Track quotes, payment, assigned teams, documents and completion milestones." />{roles.includes('seller') && <div className="role-switch"><button className={role === 'buyer' ? 'active' : ''} onClick={() => setRole('buyer')}>Buyer</button><button className={role === 'seller' ? 'active' : ''} onClick={() => setRole('seller')}>Seller</button></div>}<div className="module-toolbar"><label><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search booking number or service" /></label><label><SlidersHorizontal /><select value={status} onChange={(event) => setStatus(event.target.value)}>{['all', 'submitted', 'under_review', 'documents_required', 'in_progress', 'completed', 'cancelled'].map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><Link className="button button--primary" to="/services">Book service</Link></div>{query.loading ? <TradeSkeleton /> : query.error ? <p className="inline-error">{query.error.message}</p> : items.length ? <div className="service-request-list">{items.map((item) => <Link key={resolveId(item)} to={`/services/requests/${resolveId(item)}`}><i><CalendarDays /></i><div><span>{item.serviceTitle}</span><h2>{item.requestNumber}</h2><p>{item.details || 'Trade service booking'}</p><small>{new Date(item.createdAt).toLocaleDateString()} · {item.role}</small></div><aside><StatusBadge status={item.status} /><b><Money value={item.pricing?.totalPayable} currency={item.pricing?.currency} /></b><small>Payment {item.paymentStatus}</small></aside><ArrowRight /></Link>)}</div> : <div className="empty-results"><CalendarDays /><h2>No service bookings</h2><p>Your submitted trade-service requests will appear here.</p><Link className="button button--primary" to="/services">Browse services</Link></div>}</div></AppShell> }
