/* eslint-disable react-hooks/set-state-in-effect */
import { CalendarClock, Check, CreditCard, Crown, History, RefreshCw, ShieldCheck } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createSubscriptionOrder, fetchSubscription, fetchSubscriptionPlans, setSubscriptionAutoRenew, verifySubscriptionPayment } from '../api/verification'

const money=value=>`₹${Number(value||0).toLocaleString('en-IN')}`
const features=plan=>Array.isArray(plan.features)?plan.features:[...(plan.features?.highlighted||[]),...(plan.features?.core||[])].slice(0,8)
function loadRazorpay(){if(window.Razorpay)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=resolve;script.onerror=()=>reject(new Error('Secure checkout could not be loaded.'));document.head.appendChild(script)})}

export default function SubscriptionPage(){
  const [data,setData]=useState(null),[plans,setPlans]=useState([]),[duration,setDuration]=useState('monthly'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const load=useCallback(async()=>{const [current,catalog]=await Promise.all([fetchSubscription('seller'),fetchSubscriptionPlans('seller')]);setData(current);setPlans(catalog?.plans||catalog||[])},[])
  useEffect(()=>{load().catch(error=>setMessage(error.message))},[load])
  async function checkout(plan){setBusy(true);setMessage('');try{await loadRazorpay();const planType=plan.key||plan.planType;const order=await createSubscriptionOrder({planType,duration});const razorpay=new window.Razorpay({key:order.key,amount:order.amount,currency:order.currency,name:'EsyGlob',description:`${plan.name} subscription`,order_id:order.orderId,prefill:order.user,handler:async response=>{try{await verifySubscriptionPayment({razorpayPaymentId:response.razorpay_payment_id,razorpayOrderId:response.razorpay_order_id,razorpaySignature:response.razorpay_signature,planType,duration});setMessage('Payment verified. Your membership is active.');await load()}catch(error){setMessage(error.message)}}});razorpay.open()}catch(error){setMessage(error.message)}finally{setBusy(false)}}
  const subscription=data?.subscription||{},current=data?.plan||{}
  return <AppShell><main className="container subscription-page"><header className="subscription-hero"><Crown/><div><span className="eyebrow">Seller membership</span><h1>Grow with the right plan</h1><p>Verification visibility, sourcing tools, AI credits and seller limits in one transparent membership.</p></div></header>{message&&<div className="verification-alert">{message}<button onClick={()=>setMessage('')}>Dismiss</button></div>}<section className="subscription-current"><div><ShieldCheck/><span><small>Current plan</small><b>{current.name||subscription.sellerPlan||'Free seller'}</b></span></div><div><CalendarClock/><span><small>Valid until</small><b>{subscription.expiryDate?new Date(subscription.expiryDate).toLocaleDateString():'No expiry'}</b></span></div><div><RefreshCw/><span><small>Auto renewal</small><b>{subscription.autoRenew?'Enabled':'Disabled'}</b></span><button onClick={async()=>{await setSubscriptionAutoRenew(!subscription.autoRenew);load()}}>Change</button></div></section><div className="billing-toggle">{['monthly','quarterly','yearly'].map(item=><button className={duration===item?'active':''} onClick={()=>setDuration(item)} key={item}>{item}</button>)}</div><section className="plan-grid">{plans.map(plan=>{const price=plan.prices?.[duration]?.amount??plan.prices?.[duration]??0,isCurrent=plan.key===subscription.planKey||plan.key===subscription.sellerPlan;return <article className={plan.isPopular||plan.recommended?'recommended':''} key={plan.key||plan.name}>{(plan.isPopular||plan.recommended)&&<em>Recommended</em>}<h2>{plan.name}</h2><p>{plan.description||'Built for global marketplace growth.'}</p><strong>{money(price)}<small> / {duration}</small></strong><ul>{features(plan).map(feature=><li key={String(feature)}><Check/>{typeof feature==='string'?feature:feature.label}</li>)}</ul><button className={`button ${isCurrent?'button--ghost':'button--primary'} button--full`} disabled={busy||isCurrent||Number(price)===0} onClick={()=>checkout(plan)}>{isCurrent?'Current plan':Number(price)>Number(current.prices?.[duration]?.amount||0)?'Upgrade':'Change plan'}</button></article>})}</section><section className="module-panel payment-history"><h2><History/>Payment history</h2>{subscription.paymentHistoryIds?.length?<div>{subscription.paymentHistoryIds.map(item=><p key={item._id||item}><CreditCard/><span><b>{item.description||'Subscription payment'}</b><small>{item.createdAt?new Date(item.createdAt).toLocaleDateString():String(item)}</small></span><strong>{money(item.amount)}</strong></p>)}</div>:<p className="factory-note">No subscription payments yet.</p>}</section></main></AppShell>
}
