import { ArrowLeft, Bell, BriefcaseBusiness, CheckCircle2, FileSignature, FileText, History, MessageSquare, PackageCheck, ReceiptText, ShieldCheck, Truck, UserRound } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { fetchUnifiedTradeWorkspace, startSellerOrder } from '../api/trade'
import { createReview } from '../api/marketplace'
import AppShell from '../components/AppShell'
import TradeWorkspace from '../components/TradeWorkspace'
import { DetailItem, Money, StatusBadge } from '../components/TradeUI'
import useAsyncData from '../hooks/useAsyncData'
import { getRealtimeClient } from '../realtime/socket'
import { displayName, resolveId } from '../utils/trade'
import { Field } from './RfqCreatePage'
import { TradeSkeleton } from './RfqsPage'

const label=value=>String(value||'').replaceAll('_',' ')
const date=value=>value?new Date(value).toLocaleString():'—'
export default function TradeWorkspacePage(){
  const {entityType,entityId}=useParams(),navigate=useNavigate(),[params]=useSearchParams()
  const query=useAsyncData(useCallback(()=>fetchUnifiedTradeWorkspace(entityType,entityId),[entityId,entityType]))
  const reloadWorkspace=query.reload
  useEffect(()=>{let socket;const refresh=()=>reloadWorkspace();getRealtimeClient().then(client=>{socket=client;client.on('quotation_updated',refresh);client.on('order_updated',refresh)}).catch(()=>{});return()=>{socket?.off('quotation_updated',refresh);socket?.off('order_updated',refresh)}},[reloadWorkspace])
  const [section,setSection]=useState(params.get('section')||'overview')
  if(query.loading)return <AppShell><main className="container unified-trade-page"><TradeSkeleton/></main></AppShell>
  if(query.error)return <AppShell><main className="container unified-trade-page"><p className="inline-error">{query.error.message}</p></main></AppShell>
  const data=query.data||{},quotation=data.activeQuotation||{},order=data.order||{},rfq=data.rfq||{},product=data.product||{}
  const workspaceEntity=order._id?{type:'order',id:resolveId(order)}:quotation._id?{type:'quotation',id:resolveId(quotation)}:{type:'rfq',id:resolveId(rfq)}
  const tabs=[['overview','Overview'],['commercial','RFQ & quotations'],['documents','Notes & documents'],['execution','Order & logistics'],['activity','Activity history']]
  return <AppShell><main className="container unified-trade-page"><button className="back-link" onClick={()=>navigate(-1)}><ArrowLeft/>Back</button><header className="unified-trade-hero"><div><span className="eyebrow"><BriefcaseBusiness/> Trade Workspace · {data.tradeId}</span><h1>{product.name||rfq.title||order.products?.[0]?.name||'Enterprise trade'}</h1><p>One synchronized workspace for every official record between buyer and seller.</p></div><div><StatusBadge status={data.lifecycle?.currentStatus||quotation.status||rfq.status}/><small>Signed in as {data.actorRole}</small></div></header><nav className="unified-trade-tabs">{tabs.map(([key,text])=><button className={section===key?'active':''} key={key} onClick={()=>setSection(key)}>{text}</button>)}</nav>
  {section==='overview'&&<Overview data={data} product={product} rfq={rfq} quotation={quotation} order={order}/>} 
  {section==='commercial'&&<Commercial data={data} rfq={rfq} active={quotation}/>} 
  {section==='documents'&&<div className="unified-trade-content"><TradeWorkspace entityType={workspaceEntity.type} entityId={workspaceEntity.id}/><DocumentLedger documents={data.documents}/></div>}
  {section==='execution'&&<Execution data={data} order={order} quotation={quotation} onStarted={query.reload}/>} 
  {section==='activity'&&<Activity data={data} onUpdated={query.reload}/>} 
  </main></AppShell>
}

function Overview({data,product,rfq,quotation,order}){const next=data.lifecycle?.allowedActions||[];return <div className="unified-trade-grid"><section className="module-panel trade-stage-card"><div><PackageCheck/><span><small>Current stage</small><b>{label(data.lifecycle?.currentStatus)}</b></span></div><p>Previous: {label(data.lifecycle?.previousStatus||'Starting stage')}</p>{next.length>0&&<p>Available actions: {next.map(item=>label(item.action)).join(', ')}</p>}</section><section className="module-panel"><h2>Product and supplier</h2><dl className="trade-detail-grid"><DetailItem label="Product">{product.name||rfq.title}</DetailItem><DetailItem label="Supplier">{displayName(product.sellerId,'Supplier')}</DetailItem><DetailItem label="MOQ">{product.minimumOrderQuantity||quotation.minimumOrderQuantity||rfq.minimumOrderQuantity}</DetailItem><DetailItem label="Verification">{product.sellerId?.isVerified?'Verified supplier':'Marketplace supplier'}</DetailItem><DetailItem label="Variants">{product.variants?.length||0}</DetailItem><DetailItem label="Trade assurance">{order.tradeAssurance?.isProtected?'Protected':'Pending order'}</DetailItem></dl></section><section className="module-panel"><h2>Connected records</h2><div className="workspace-record-links">{rfq._id&&<Link to={`/rfqs/${resolveId(rfq)}`}><FileText/>RFQ <StatusBadge status={rfq.status}/></Link>}{quotation._id&&<Link to={`/quotations/${resolveId(quotation)}`}><ReceiptText/>Quotation v{quotation.revisionNumber} <StatusBadge status={quotation.status}/></Link>}{order._id&&<Link to={`/orders/${resolveId(order)}`}><PackageCheck/>Order {order.orderNumber} <StatusBadge status={order.status}/></Link>}{data.chats?.[0]&&<Link to={`/messages/${resolveId(data.chats[0])}`}><MessageSquare/>Open communication chat</Link>}</div></section><section className="module-panel"><h2><FileSignature/>Official Final Quotation</h2><p>Status: <b>{label(data.finalQuotation?.status||'not started')}</b></p><p>Reference: {quotation.finalQuotation?.finalQuotationNumber||'—'}</p><p>The Buyer-signed Final Quotation is the single commercial document that enables Start Order.</p></section></div>}

function Commercial({data,rfq,active}){return <div className="unified-trade-content"><section className="module-panel"><div className="compact-heading"><h2>RFQ</h2>{rfq._id&&<Link to={`/rfqs/${resolveId(rfq)}`}>Open full RFQ</Link>}</div><dl className="trade-detail-grid"><DetailItem label="Quantity">{rfq.quantity} {rfq.unit}</DetailItem><DetailItem label="Target price"><Money value={rfq.targetPrice} currency={rfq.currency}/></DetailItem><DetailItem label="Destination">{rfq.deliveryCountry}</DetailItem><DetailItem label="Delivery">{rfq.deliveryTimeline||rfq.deliveryDate}</DetailItem><DetailItem label="Shipping preference">{rfq.shippingPreference||rfq.incoterms}</DetailItem><DetailItem label="Status">{label(rfq.status)}</DetailItem></dl><p>{rfq.description||rfq.specifications}</p></section><section className="module-panel"><h2>Quotation versions</h2><div className="workspace-version-list">{(data.quotations||[]).map(item=><article className={resolveId(item)===resolveId(active)?'active':''} key={resolveId(item)}><div><b>Version {item.revisionNumber||1}</b><StatusBadge status={item.status}/></div><p><Money value={item.totalPrice} currency={item.currency}/> · MOQ {item.minimumOrderQuantity} · {item.leadTime} {item.leadTimeUnit}</p><Link to={`/quotations/${resolveId(item)}`}>Review official quotation</Link></article>)}</div>{active.revisionHistory?.length>0&&<div className="workspace-revisions"><h3>Immutable revision history</h3>{[...active.revisionHistory].reverse().map((item,index)=><p key={item._id||index}><b>V{item.version||index+1}</b> · {item.reason||item.notes||'Commercial terms revised'} · {date(item.revisedAt)}</p>)}</div>}</section></div>}

function DocumentLedger({documents=[]}){return <section className="module-panel"><h2>Complete document ledger</h2><div className="workspace-document-ledger">{documents.map((item,index)=><article key={`${item.entityType}-${item._id||index}`}><FileText/><span><b>{item.title||item.filename}</b><small>{label(item.documentType)} · {item.entityType} · v{item.version||1} · {label(item.status)}</small></span>{item.previewUrl&&<a href={item.previewUrl} target="_blank" rel="noreferrer">Preview</a>}</article>)}</div>{!documents.length&&<p className="empty-copy">No trade documents have been added.</p>}</section>}

function Execution({data,order,quotation,onStarted}){return <div className="unified-trade-content">{data.actorRole==='seller'&&!order._id&&quotation.status==='final_quotation_signed'&&<SellerStartOrder data={data} quotation={quotation} onStarted={onStarted}/>}<section className="module-panel"><h2>Order execution</h2>{order._id?<><dl className="trade-detail-grid"><DetailItem label="Order">{order.orderNumber}</DetailItem><DetailItem label="Final price"><Money value={order.totalAmount} currency={order.currency}/></DetailItem><DetailItem label="Quantity">{order.quantity} {order.unit}</DetailItem><DetailItem label="Taxes"><Money value={order.taxAmount} currency={order.currency}/></DetailItem><DetailItem label="Shipping"><Money value={order.shippingCost} currency={order.currency}/></DetailItem><DetailItem label="Logistics">{label(order.checkout?.logisticsSnapshot?.label||order.shippingMethod||'buyer selection pending')}</DetailItem></dl><Link className="button button--primary" to={`/orders/${resolveId(order)}${data.actorRole==='seller'?'?role=seller':''}`}>Open operational order</Link></>:<p>Order becomes available immediately after the Buyer signs the Final Quotation.</p>}</section><section className="module-panel"><h2><Truck/>Logistics and payment</h2><p>Shipment: <b>{label(data.shipment?.status||'not booked')}</b></p><p>Tracking: {data.shipment?.trackingNumber||order.trackingNumber||'—'}</p><p>Payment: <b>{label(data.payment?.status||order.paymentStatus||'not started')}</b></p><p>Invoice: {data.invoice?.invoiceNumber||'Generated after verified payment'}</p></section></div>}

function SellerStartOrder({data,quotation,onStarted}){const product=data.product||{},rfq=data.rfq||{};const [form,setForm]=useState({productId:resolveId(product),quantity:quotation.suppliedQuantity||rfq.quantity||'',minimumOrderQuantity:quotation.minimumOrderQuantity||product.minimumOrderQuantity||1,unitPrice:quotation.unitPrice||'',shippingCost:quotation.shippingCost||0,taxAmount:quotation.taxes?.amount||0,discount:0,productionTime:quotation.productionTime||quotation.leadTime||'',leadTime:quotation.leadTime||'',paymentTerms:quotation.paymentTerms||'negotiable',deliveryTerms:quotation.shippingTerms||quotation.incoterms||rfq.incoterms||'FOB',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const total=useMemo(()=>Math.max(0,Number(form.unitPrice||0)*Number(form.quantity||0)+Number(form.shippingCost||0)+Number(form.taxAmount||0)-Number(form.discount||0)),[form]);async function start(){setBusy(true);setError('');try{await startSellerOrder({...form,rfqId:resolveId(rfq),quotationId:resolveId(quotation),quantity:Number(form.quantity),minimumOrderQuantity:Number(form.minimumOrderQuantity),unitPrice:Number(form.unitPrice),shippingCost:Number(form.shippingCost),taxAmount:Number(form.taxAmount),discount:Number(form.discount)});await onStarted()}catch(next){setError(next.message);setBusy(false)}}return <section className="module-panel seller-order-config"><span className="eyebrow"><ShieldCheck/>Final Quotation signed</span><h2>Start Order</h2><p>The signed Final Quotation is locked and automatically populates these execution terms.</p><div className="form-grid form-grid--3">{[['quantity','Final quantity'],['minimumOrderQuantity','Final MOQ'],['unitPrice','Unit price'],['shippingCost','Shipping charges'],['taxAmount','Taxes'],['discount','Discount']].map(([key,text])=><Field label={text} key={key}><input type="number" min="0" value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></Field>)}</div><div className="form-grid"><Field label="Production time"><input value={form.productionTime} onChange={event=>setForm({...form,productionTime:event.target.value})}/></Field><Field label="Delivery / shipping"><input value={form.deliveryTerms} onChange={event=>setForm({...form,deliveryTerms:event.target.value})}/></Field></div><Field label="Payment terms"><input value={form.paymentTerms} onChange={event=>setForm({...form,paymentTerms:event.target.value})}/></Field><Field label="Order note"><textarea value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></Field><div className="quote-total"><span>Buyer checkout subtotal</span><b><Money value={total} currency={quotation.currency}/></b></div>{error&&<p className="action-error">{error}</p>}<button className="button button--primary button--full" disabled={busy||!form.productId} onClick={start}><CheckCircle2/>{busy?'Starting order…':'Start Order'}</button></section>}

function Activity({data,onUpdated}){return <div className="unified-trade-content"><section className="module-panel"><h2><History/>Complete activity timeline</h2><div className="order-timeline">{(data.timeline||[]).map((item,index)=><span key={`${item.entityType}-${item._id||index}`}><i/><div><b>{label(item.action||item.status)}</b><p>{item.message||item.note} <small>· {item.entityType}</small></p><small>{date(item.createdAt||item.timestamp)} · {label(item.actorRole||'system')} · {label(item.previousStatus)} → {label(item.newStatus||item.status)}</small></div></span>)}</div></section><section className="module-panel"><h2><Bell/>Workspace notifications</h2><div className="workspace-notifications">{(data.notifications||[]).map(item=><article key={resolveId(item)}><Bell/><span><b>{item.title}</b><p>{item.description}</p><small>{date(item.createdAt)}</small></span></article>)}</div></section><section className="module-panel"><h2><UserRound/>Reviews</h2>{data.reviews?.length?data.reviews.map(item=><p key={resolveId(item)}><b>{item.rating?.overall}/5</b> · {item.title||item.comment}</p>):<p>Review becomes available after delivery confirmation.</p>}{data.actorRole==='buyer'&&['delivered','completed','closed'].includes(data.order?.status)&&!data.reviews?.length&&<ReviewComposer data={data} onUpdated={onUpdated}/>}</section></div>}

function ReviewComposer({data,onUpdated}){const [rating,setRating]=useState(5),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(){setBusy(true);setError('');try{await createReview({orderId:resolveId(data.order),productId:resolveId(data.product),sellerId:resolveId(data.order?.sellerId||data.product?.sellerId),rating,title:'Trade experience',comment});await onUpdated()}catch(next){setError(next.message);setBusy(false)}}return <div className="workspace-review-compose"><Field label="Rating"><select value={rating} onChange={event=>setRating(Number(event.target.value))}>{[5,4,3,2,1].map(value=><option value={value} key={value}>{value} stars</option>)}</select></Field><Field label="Review"><textarea value={comment} onChange={event=>setComment(event.target.value)} placeholder="Quality, communication, shipping and overall trade experience"/></Field>{error&&<p className="action-error">{error}</p>}<button className="button button--primary" disabled={busy||comment.trim().length<5} onClick={submit}>{busy?'Publishing…':'Publish rating & review'}</button></div>}
